/* config/config.h.  Generated by configure.  */
/* config/config.h.in.  Generated from configure.ac by autoheader.  */

/* Name of package */
#define PACKAGE "lhapdf"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "lhapdf@cedar.ac.uk"

/* Define to the full name of this package. */
#define PACKAGE_NAME "LHAPDF"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "LHAPDF 4.2"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "lhapdf"

/* Define to the version of this package. */
#define PACKAGE_VERSION "4.2"

/* Version number of package */
#define VERSION "4.2"
