c This file has been generated automatically by FeynRules
c Version: 1.5.9   Date: 8. 7. 2009,    11:36

      double precision G
      common/strong/ G

      double complex gal(2)
      common/weak/ gal

      double precision DUM0
      common/FRDUM0/ DUM0

      double precision DUM1
      common/FRDUM1/ DUM1


c Masses : 
      double precision MC,MB,MT,MTA,MZ,MW,MH
      common/masses/ MC,MB,MT,MTA,MZ,MW,MH

c Widths : 
      double precision WT,WZ,WW,WH
      common/widths/ WT,WZ,WW,WH

c Interactions associated with Standard_Model:
      double precision MGVX3,MGVX1,MGVX5,MGVX4,MGVX7,MGVX2,MGVX6,MG
     +VX8
      common/real_coupl_Standard_Model/ MGVX3,MGVX1,MGVX5,MGVX4,MGV
     +X7,MGVX2,MGVX6,MGVX8

      double complex MGVX53,MGVX52,MGVX55,MGVX57,MGVX54,MGVX56
      common/comp_coupl_Standard_Model/ MGVX53,MGVX52,MGVX55,MGVX57
     +,MGVX54,MGVX56

      double complex MGVX18(2),MGVX24(2),MGVX43(2),MGVX49(2),MGVX59
     +(2),MGVX15(2),MGVX21(2),MGVX58(2),MGVX60(2),MGVX61(2),MGVX27
     +(2),MGVX28(2),MGVX30(2),MGVX31(2),MGVX36(2),MGVX37(2),MGVX38
     +(2),MGVX39(2),MGVX40(2),MGVX46(2),GG(2)
      common/chiral_coupl_Standard_Model/ MGVX18,MGVX24,MGVX43,MGVX
     +49,MGVX59,MGVX15,MGVX21,MGVX58,MGVX60,MGVX61,MGVX27,MGVX28,M
     +GVX30,MGVX31,MGVX36,MGVX37,MGVX38,MGVX39,MGVX40,MGVX46,GG

