c This file has been generated automatically by FeynRules


c Version: 1.5.9   Date: 8. 7. 2009,    11:36
      write(*,*)  ' Couplings of Standard_Model'
      write(*,*)  ' ---------------------------------'
      write(*,*)  ''
      write(*,*)  ' Real couplings : '
      write(*,1) 'MGVX3=',MGVX3
      write(*,1) 'MGVX1=',MGVX1
      write(*,1) 'MGVX5=',MGVX5
      write(*,1) 'MGVX4=',MGVX4
      write(*,1) 'MGVX7=',MGVX7
      write(*,1) 'MGVX2=',MGVX2
      write(*,1) 'MGVX6=',MGVX6
      write(*,1) 'MGVX8=',MGVX8
      write(*,*)  ''
      write(*,*)  ' Complex couplings : '
      write(*,2) 'MGVX53=',MGVX53
      write(*,2) 'MGVX52=',MGVX52
      write(*,2) 'MGVX55=',MGVX55
      write(*,2) 'MGVX57=',MGVX57
      write(*,2) 'MGVX54=',MGVX54
      write(*,2) 'MGVX56=',MGVX56
      write(*,*)  ''
      write(*,*)  ' Left/Right couplings : '
      write(*,4) 'MGVX18(L)=',MGVX18(1),'MGVX18(R)=',MGVX18(2)
      write(*,4) 'MGVX24(L)=',MGVX24(1),'MGVX24(R)=',MGVX24(2)
      write(*,4) 'MGVX43(L)=',MGVX43(1),'MGVX43(R)=',MGVX43(2)
      write(*,4) 'MGVX49(L)=',MGVX49(1),'MGVX49(R)=',MGVX49(2)
      write(*,4) 'MGVX59(L)=',MGVX59(1),'MGVX59(R)=',MGVX59(2)
      write(*,4) 'MGVX15(L)=',MGVX15(1),'MGVX15(R)=',MGVX15(2)
      write(*,4) 'MGVX21(L)=',MGVX21(1),'MGVX21(R)=',MGVX21(2)
      write(*,4) 'MGVX58(L)=',MGVX58(1),'MGVX58(R)=',MGVX58(2)
      write(*,4) 'MGVX60(L)=',MGVX60(1),'MGVX60(R)=',MGVX60(2)
      write(*,4) 'MGVX61(L)=',MGVX61(1),'MGVX61(R)=',MGVX61(2)
      write(*,4) 'MGVX27(L)=',MGVX27(1),'MGVX27(R)=',MGVX27(2)
      write(*,4) 'MGVX28(L)=',MGVX28(1),'MGVX28(R)=',MGVX28(2)
      write(*,4) 'MGVX30(L)=',MGVX30(1),'MGVX30(R)=',MGVX30(2)
      write(*,4) 'MGVX31(L)=',MGVX31(1),'MGVX31(R)=',MGVX31(2)
      write(*,4) 'MGVX36(L)=',MGVX36(1),'MGVX36(R)=',MGVX36(2)
      write(*,4) 'MGVX37(L)=',MGVX37(1),'MGVX37(R)=',MGVX37(2)
      write(*,4) 'MGVX38(L)=',MGVX38(1),'MGVX38(R)=',MGVX38(2)
      write(*,4) 'MGVX39(L)=',MGVX39(1),'MGVX39(R)=',MGVX39(2)
      write(*,4) 'MGVX40(L)=',MGVX40(1),'MGVX40(R)=',MGVX40(2)
      write(*,4) 'MGVX46(L)=',MGVX46(1),'MGVX46(R)=',MGVX46(2)
      write(*,4) 'GG(L)=',GG(1),'GG(R)=',GG(2)
      write(*,*)  ' '
      write(*,*)  ' '
