c This file has been generated automatically by FeynRules


c Version: 1.5.9   Date: 8. 7. 2009,    11:36
      write(1,11) 'MGVX3',MGVX3
      write(1,11) 'MGVX1',MGVX1
      write(1,11) 'MGVX5',MGVX5
      write(1,11) 'MGVX4',MGVX4
      write(1,11) 'MGVX7',MGVX7
      write(1,11) 'MGVX2',MGVX2
      write(1,11) 'MGVX6',MGVX6
      write(1,11) 'MGVX8',MGVX8
      write(1,12) 'MGVX53',MGVX53
      write(1,12) 'MGVX52',MGVX52
      write(1,12) 'MGVX55',MGVX55
      write(1,12) 'MGVX57',MGVX57
      write(1,12) 'MGVX54',MGVX54
      write(1,12) 'MGVX56',MGVX56
      write(1,13) 'MGVX18',MGVX18(1),MGVX18(2)
      write(1,13) 'MGVX24',MGVX24(1),MGVX24(2)
      write(1,13) 'MGVX43',MGVX43(1),MGVX43(2)
      write(1,13) 'MGVX49',MGVX49(1),MGVX49(2)
      write(1,13) 'MGVX59',MGVX59(1),MGVX59(2)
      write(1,13) 'MGVX15',MGVX15(1),MGVX15(2)
      write(1,13) 'MGVX21',MGVX21(1),MGVX21(2)
      write(1,13) 'MGVX58',MGVX58(1),MGVX58(2)
      write(1,13) 'MGVX60',MGVX60(1),MGVX60(2)
      write(1,13) 'MGVX61',MGVX61(1),MGVX61(2)
      write(1,13) 'MGVX27',MGVX27(1),MGVX27(2)
      write(1,13) 'MGVX28',MGVX28(1),MGVX28(2)
      write(1,13) 'MGVX30',MGVX30(1),MGVX30(2)
      write(1,13) 'MGVX31',MGVX31(1),MGVX31(2)
      write(1,13) 'MGVX36',MGVX36(1),MGVX36(2)
      write(1,13) 'MGVX37',MGVX37(1),MGVX37(2)
      write(1,13) 'MGVX38',MGVX38(1),MGVX38(2)
      write(1,13) 'MGVX39',MGVX39(1),MGVX39(2)
      write(1,13) 'MGVX40',MGVX40(1),MGVX40(2)
      write(1,13) 'MGVX46',MGVX46(1),MGVX46(2)
      write(1,13) 'GG',GG(1),GG(2)
