c This file has been generated automatically by FeynRules
c Version: 1.5.9   Date: 8. 7. 2009,    11:36

c External Parameters :
      double precision cabi,aEWM1,Gf,aS,ymc,ymb,ymt,ymtau
      common/external_params/ cabi,aEWM1,Gf,aS,ymc,ymb,ymt,ymtau

c Internal Parameters :
      double precision aEW,sw2,ee,cw,sw,gw,g1,v,lam,muH,ytau,yc,yt,
     +yb,Sqrt2,SqrtPi,Pgw2,Psw2,Pcw2,GGT1
      common/internal_params_R/ aEW,sw2,ee,cw,sw,gw,g1,v,lam,muH,yt
     +au,yc,yt,yb,Sqrt2,SqrtPi,Pgw2,Psw2,Pcw2,GGT1
      double complex CKM11,CKM12,CKM21,CKM22,CONJCKM21,CONJCKM11,CO
     +NJCKM22,CONJCKM12
      common/internal_params_C/ CKM11,CKM12,CKM21,CKM22,CONJCKM21,C
     +ONJCKM11,CONJCKM22,CONJCKM12
