      write(*,*)  ' External Params            '
      write(*,*)  ' ---------------------------'
      write(*,1) 'cabi=',cabi
      write(*,1) 'aEWM1=',aEWM1
      write(*,1) 'Gf=',Gf
      write(*,1) 'aS=',aS
      write(*,1) 'ymc=',ymc
      write(*,1) 'ymb=',ymb
      write(*,1) 'ymt=',ymt
      write(*,1) 'ymtau=',ymtau
      write(*,*)  ''
      write(*,*)  ' Internal Params            '
      write(*,*)  ' ---------------------------'
      write(*,1) 'aEW=',aEW
      write(*,1) 'sw2=',sw2
      write(*,1) 'ee=',ee
      write(*,1) 'cw=',cw
      write(*,1) 'sw=',sw
      write(*,1) 'gw=',gw
      write(*,1) 'g1=',g1
      write(*,1) 'G=',G
      write(*,1) 'v=',v
      write(*,1) 'lam=',lam
      write(*,1) 'muH=',muH
      write(*,1) 'ytau=',ytau
      write(*,1) 'yc=',yc
      write(*,1) 'yt=',yt
      write(*,1) 'yb=',yb
      write(*,2) 'CKM11=',CKM11
      write(*,2) 'CKM12=',CKM12
      write(*,2) 'CKM21=',CKM21
      write(*,2) 'CKM22=',CKM22
      write(*,1) 'Sqrt2=',Sqrt2
      write(*,1) 'SqrtPi=',SqrtPi
      write(*,1) 'Pgw2=',Pgw2
      write(*,1) 'Psw2=',Psw2
      write(*,1) 'Pcw2=',Pcw2
      write(*,2) 'CONJCKM21=',CONJCKM21
      write(*,2) 'CONJCKM11=',CONJCKM11
      write(*,2) 'CONJCKM22=',CONJCKM22
      write(*,2) 'CONJCKM12=',CONJCKM12
      write(*,1) 'GGT1=',GGT1
      write(*,*)  ''
      write(*,*)  ' Masses                     '
      write(*,*)  ' ---------------------------'
      write(*,3) 'MC=',MC
      write(*,3) 'MB=',MB
      write(*,3) 'MT=',MT
      write(*,3) 'MTA=',MTA
      write(*,3) 'MZ=',MZ
      write(*,3) 'MW=',MW
      write(*,3) 'MH=',MH
      write(*,*)  ''
      write(*,*)  ' Widths                     '
      write(*,*)  ' ---------------------------'
      write(*,3) 'WT=',WT
      write(*,3) 'WZ=',WZ
      write(*,3) 'WW=',WW
      write(*,3) 'WH=',WH
      write(*,*)  ''
