###########################################################
##							 ##
##		ordering width information		 ##
##		**************************		 ##
##							 ##
##	Authors: Pierre Artoisenet (UCL-CP3)		 ##
##	         Olivier Mattelaer (UCL-CP3)		 ##
##							 ##
###########################################################
##    file generated automatically                       ##
##	Transfer functions type : dbl_gauss_pt_jet		 ##
###########################################################
## TAG         VALUE
  DELTA        e,m,t  	
  THIN 	       
  LARGE        a,b,j,g
   X                0
