      call LHA_get_real(npara,param,value,"CKMI11",CKMI11,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"CKMI12",CKMI12,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"CKMI13",CKMI13,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"CKMI21",CKMI21,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"CKMI22",CKMI22,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"CKMI23",CKMI23,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"CKMI31",CKMI31,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"CKMI32",CKMI32,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"CKMI33",CKMI33,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"CKMR11",CKMR11,"9.745891"
     +//"4400000E-01")
      call LHA_get_real(npara,param,value,"CKMR12",CKMR12,"2.240000"
     +//"0000000E-01")
      call LHA_get_real(npara,param,value,"CKMR13",CKMR13,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"CKMR21",CKMR21,"-2.24000"
     +//"0000000E-01")
      call LHA_get_real(npara,param,value,"CKMR22",CKMR22,"9.745891"
     +//"4400000E-01")
      call LHA_get_real(npara,param,value,"CKMR23",CKMR23,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"CKMR31",CKMR31,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"CKMR32",CKMR32,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"CKMR33",CKMR33,"1.000000"
     +//"0000000E+00")
      call LHA_get_real(npara,param,value,"l1",l1,"1.0000000000000E"
     +//"+00")
      call LHA_get_real(npara,param,value,"l2",l2,"1.0000000000000E"
     +//"+00")
      call LHA_get_real(npara,param,value,"l3",l3,"1.0000000000000E"
     +//"+00")
      call LHA_get_real(npara,param,value,"l4",l4,"5.0000000000000E"
     +//"-01")
      call LHA_get_real(npara,param,value,"l5",l5,"4.0000000000000E"
     +//"-01")
      call LHA_get_real(npara,param,value,"lR6",lR6,"3.000000000000"
     +//"0E-01")
      call LHA_get_real(npara,param,value,"lI6",lI6,"0.00000000E+00"
     +//"")
      call LHA_get_real(npara,param,value,"lR7",lR7,"2.000000000000"
     +//"0E-01")
      call LHA_get_real(npara,param,value,"lI7",lI7,"0.00000000E+00"
     +//"")
      call LHA_get_real(npara,param,value,"TH11",TH11,"0.00000000E+"
     +//"00")
      call LHA_get_real(npara,param,value,"TH12",TH12,"7.8064408782"
     +//"535E-01")
      call LHA_get_real(npara,param,value,"TH13",TH13,"6.2497584604"
     +//"793E-01")
      call LHA_get_real(npara,param,value,"TH21",TH21,"0.00000000E+"
     +//"00")
      call LHA_get_real(npara,param,value,"TH22",TH22,"-6.249758460"
     +//"479E-01")
      call LHA_get_real(npara,param,value,"TH23",TH23,"7.8064408782"
     +//"535E-01")
      call LHA_get_real(npara,param,value,"TH31",TH31,"1.0000000000"
     +//"000E+00")
      call LHA_get_real(npara,param,value,"TH32",TH32,"0.00000000E+"
     +//"00")
      call LHA_get_real(npara,param,value,"TH33",TH33,"0.00000000E+"
     +//"00")
      call LHA_get_real(npara,param,value,"aEWM1",aEWM1,"1.27934000"
     +//"00000E+02")
      call LHA_get_real(npara,param,value,"Gf",Gf,"1.1663700000000E"
     +//"-05")
      call LHA_get_real(npara,param,value,"aS",aS,"1.1720000000000E"
     +//"-01")
      call LHA_get_real(npara,param,value,"yukd1",yukd1,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"yukd2",yukd2,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"yukd3",yukd3,"3.00000000"
     +//"00000E+00")
      call LHA_get_real(npara,param,value,"GDI11",GDI11,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"GDI12",GDI12,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"GDI13",GDI13,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"GDI21",GDI21,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"GDI22",GDI22,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"GDI23",GDI23,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"GDI31",GDI31,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"GDI32",GDI32,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"GDI33",GDI33,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"GDR11",GDR11,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"GDR12",GDR12,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"GDR13",GDR13,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"GDR21",GDR21,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"GDR22",GDR22,"4.00000000"
     +//"00000E-01")
      call LHA_get_real(npara,param,value,"GDR23",GDR23,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"GDR31",GDR31,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"GDR32",GDR32,"2.00000000"
     +//"00000E-01")
      call LHA_get_real(npara,param,value,"GDR33",GDR33,"5.00000000"
     +//"00000E+00")
      call LHA_get_real(npara,param,value,"GLI11",GLI11,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"GLI12",GLI12,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"GLI13",GLI13,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"GLI21",GLI21,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"GLI22",GLI22,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"GLI23",GLI23,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"GLI31",GLI31,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"GLI32",GLI32,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"GLI33",GLI33,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"GLR11",GLR11,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"GLR12",GLR12,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"GLR13",GLR13,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"GLR21",GLR21,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"GLR22",GLR22,"1.00000000"
     +//"00000E-01")
      call LHA_get_real(npara,param,value,"GLR23",GLR23,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"GLR31",GLR31,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"GLR32",GLR32,"5.00000000"
     +//"00000E-01")
      call LHA_get_real(npara,param,value,"GLR33",GLR33,"3.00000000"
     +//"00000E+00")
      call LHA_get_real(npara,param,value,"GUI11",GUI11,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"GUI12",GUI12,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"GUI13",GUI13,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"GUI21",GUI21,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"GUI22",GUI22,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"GUI23",GUI23,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"GUI31",GUI31,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"GUI32",GUI32,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"GUI33",GUI33,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"GUR11",GUR11,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"GUR12",GUR12,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"GUR13",GUR13,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"GUR21",GUR21,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"GUR22",GUR22,"2.00000000"
     +//"00000E+00")
      call LHA_get_real(npara,param,value,"GUR23",GUR23,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"GUR31",GUR31,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"GUR32",GUR32,"1.00000000"
     +//"00000E+00")
      call LHA_get_real(npara,param,value,"GUR33",GUR33,"1.00000000"
     +//"00000E+02")
      call LHA_get_real(npara,param,value,"yukl1",yukl1,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"yukl2",yukl2,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"yukl3",yukl3,"1.77700000"
     +//"00000E+00")
      call LHA_get_real(npara,param,value,"yuku1",yuku1,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"yuku2",yuku2,"6.00000000"
     +//"00000E-01")
      call LHA_get_real(npara,param,value,"yuku3",yuku3,"1.75000000"
     +//"00000E+02")
      call LHA_get_real(npara,param,value,"MS",MS,"1.0500000000000E"
     +//"-01")
      call LHA_get_real(npara,param,value,"MC",MC,"1.2500000000000E"
     +//"+00")
      call LHA_get_real(npara,param,value,"MB",MB,"4.2000000000000E"
     +//"+00")
      call LHA_get_real(npara,param,value,"MT",MT,"1.7430000000000E"
     +//"+02")
      call LHA_get_real(npara,param,value,"MM",MM,"1.0600000000000E"
     +//"-01")
      call LHA_get_real(npara,param,value,"MTA",MTA,"1.777000000000"
     +//"0E+00")
      call LHA_get_real(npara,param,value,"MZ",MZ,"9.1187600000000E"
     +//"+01")
      call LHA_get_real(npara,param,value,"MW",MW,"7.9829013114276E"
     +//"+01")
      call LHA_get_real(npara,param,value,"mh1",mh1,"2.844403535097"
     +//"8E+02")
      call LHA_get_real(npara,param,value,"mh2",mh2,"3.266320718287"
     +//"5E+02")
      call LHA_get_real(npara,param,value,"mh3",mh3,"3.794293037382"
     +//"2E+02")
      call LHA_get_real(npara,param,value,"mhc",mhc,"3.000000000000"
     +//"0E+02")
      call LHA_get_real(npara,param,value,"WT",WT,"1.5148707555575E"
     +//"+00")
      call LHA_get_real(npara,param,value,"WZ",WZ,"2.4126275103422E"
     +//"+00")
      call LHA_get_real(npara,param,value,"WW",WW,"2.0028844418592E"
     +//"+00")
      call LHA_get_real(npara,param,value,"Wh1",Wh1,"1.800663189818"
     +//"6E-02")
      call LHA_get_real(npara,param,value,"Wh2",Wh2,"7.088459362732"
     +//"0E+00")
      call LHA_get_real(npara,param,value,"Wh3",Wh3,"9.525902092418"
     +//"7E+00")
      call LHA_get_real(npara,param,value,"whc",whc,"1.727254564949"
     +//"8E+00")
