c This file has been generated automatically by FeynRules


c Version: 1.4.0   Date: 15. 7. 2009,    16:23
      write(*,*)  ' Couplings of MUED'
      write(*,*)  ' ---------------------------------'
      write(*,*)  ''
      write(*,*)  ' Real couplings : '
      write(*,1) 'MGVX9=',MGVX9
      write(*,1) 'MGVX3=',MGVX3
      write(*,1) 'MGVX18=',MGVX18
      write(*,1) 'MGVX10=',MGVX10
      write(*,1) 'MGVX17=',MGVX17
      write(*,1) 'MGVX33=',MGVX33
      write(*,1) 'MGVX28=',MGVX28
      write(*,1) 'MGVX4=',MGVX4
      write(*,1) 'MGVX6=',MGVX6
      write(*,1) 'MGVX7=',MGVX7
      write(*,1) 'MGVX13=',MGVX13
      write(*,1) 'MGVX35=',MGVX35
      write(*,1) 'MGVX32=',MGVX32
      write(*,1) 'MGVX38=',MGVX38
      write(*,1) 'MGVX14=',MGVX14
      write(*,1) 'MGVX37=',MGVX37
      write(*,*)  ''
      write(*,*)  ' Complex couplings : '
      write(*,2) 'MGVX2=',MGVX2
      write(*,2) 'MGVX1=',MGVX1
      write(*,2) 'MGVX16=',MGVX16
      write(*,2) 'MGVX30=',MGVX30
      write(*,2) 'MGVX15=',MGVX15
      write(*,2) 'MGVX29=',MGVX29
      write(*,*)  ''
      write(*,*)  ' Left/Right couplings : '
      write(*,4) 'MGVX24(L)=',MGVX24(1),'MGVX24(R)=',MGVX24(2)
      write(*,4) 'MGVX39(L)=',MGVX39(1),'MGVX39(R)=',MGVX39(2)
      write(*,4) 'MGVX45(L)=',MGVX45(1),'MGVX45(R)=',MGVX45(2)
      write(*,4) 'MGVX69(L)=',MGVX69(1),'MGVX69(R)=',MGVX69(2)
      write(*,4) 'MGVX72(L)=',MGVX72(1),'MGVX72(R)=',MGVX72(2)
      write(*,4) 'MGVX219(L)=',MGVX219(1),'MGVX219(R)=',MGVX219(2)
      write(*,4) 'MGVX222(L)=',MGVX222(1),'MGVX222(R)=',MGVX222(2)
      write(*,4) 'MGVX225(L)=',MGVX225(1),'MGVX225(R)=',MGVX225(2)
      write(*,4) 'MGVX231(L)=',MGVX231(1),'MGVX231(R)=',MGVX231(2)
      write(*,4) 'MGVX234(L)=',MGVX234(1),'MGVX234(R)=',MGVX234(2)
      write(*,4) 'MGVX243(L)=',MGVX243(1),'MGVX243(R)=',MGVX243(2)
      write(*,4) 'MGVX246(L)=',MGVX246(1),'MGVX246(R)=',MGVX246(2)
      write(*,4) 'MGVX267(L)=',MGVX267(1),'MGVX267(R)=',MGVX267(2)
      write(*,4) 'MGVX270(L)=',MGVX270(1),'MGVX270(R)=',MGVX270(2)
      write(*,4) 'MGVX273(L)=',MGVX273(1),'MGVX273(R)=',MGVX273(2)
      write(*,4) 'MGVX276(L)=',MGVX276(1),'MGVX276(R)=',MGVX276(2)
      write(*,4) 'MGVX303(L)=',MGVX303(1),'MGVX303(R)=',MGVX303(2)
      write(*,4) 'MGVX75(L)=',MGVX75(1),'MGVX75(R)=',MGVX75(2)
      write(*,4) 'MGVX78(L)=',MGVX78(1),'MGVX78(R)=',MGVX78(2)
      write(*,4) 'MGVX90(L)=',MGVX90(1),'MGVX90(R)=',MGVX90(2)
      write(*,4) 'MGVX87(L)=',MGVX87(1),'MGVX87(R)=',MGVX87(2)
      write(*,4) 'MGVX60(L)=',MGVX60(1),'MGVX60(R)=',MGVX60(2)
      write(*,4) 'MGVX51(L)=',MGVX51(1),'MGVX51(R)=',MGVX51(2)
      write(*,4) 'MGVX81(L)=',MGVX81(1),'MGVX81(R)=',MGVX81(2)
      write(*,4) 'MGVX291(L)=',MGVX291(1),'MGVX291(R)=',MGVX291(2)
      write(*,4) 'MGVX282(L)=',MGVX282(1),'MGVX282(R)=',MGVX282(2)
      write(*,4) 'MGVX23(L)=',MGVX23(1),'MGVX23(R)=',MGVX23(2)
      write(*,4) 'MGVX25(L)=',MGVX25(1),'MGVX25(R)=',MGVX25(2)
      write(*,4) 'MGVX26(L)=',MGVX26(1),'MGVX26(R)=',MGVX26(2)
      write(*,4) 'MGVX123(L)=',MGVX123(1),'MGVX123(R)=',MGVX123(2)
      write(*,4) 'MGVX124(L)=',MGVX124(1),'MGVX124(R)=',MGVX124(2)
      write(*,4) 'MGVX125(L)=',MGVX125(1),'MGVX125(R)=',MGVX125(2)
      write(*,4) 'MGVX132(L)=',MGVX132(1),'MGVX132(R)=',MGVX132(2)
      write(*,4) 'MGVX133(L)=',MGVX133(1),'MGVX133(R)=',MGVX133(2)
      write(*,4) 'MGVX134(L)=',MGVX134(1),'MGVX134(R)=',MGVX134(2)
      write(*,4) 'MGVX126(L)=',MGVX126(1),'MGVX126(R)=',MGVX126(2)
      write(*,4) 'MGVX127(L)=',MGVX127(1),'MGVX127(R)=',MGVX127(2)
      write(*,4) 'MGVX128(L)=',MGVX128(1),'MGVX128(R)=',MGVX128(2)
      write(*,4) 'MGVX135(L)=',MGVX135(1),'MGVX135(R)=',MGVX135(2)
      write(*,4) 'MGVX136(L)=',MGVX136(1),'MGVX136(R)=',MGVX136(2)
      write(*,4) 'MGVX137(L)=',MGVX137(1),'MGVX137(R)=',MGVX137(2)
      write(*,4) 'MGVX129(L)=',MGVX129(1),'MGVX129(R)=',MGVX129(2)
      write(*,4) 'MGVX130(L)=',MGVX130(1),'MGVX130(R)=',MGVX130(2)
      write(*,4) 'MGVX131(L)=',MGVX131(1),'MGVX131(R)=',MGVX131(2)
      write(*,4) 'MGVX138(L)=',MGVX138(1),'MGVX138(R)=',MGVX138(2)
      write(*,4) 'MGVX139(L)=',MGVX139(1),'MGVX139(R)=',MGVX139(2)
      write(*,4) 'MGVX140(L)=',MGVX140(1),'MGVX140(R)=',MGVX140(2)
      write(*,4) 'MGVX159(L)=',MGVX159(1),'MGVX159(R)=',MGVX159(2)
      write(*,4) 'MGVX160(L)=',MGVX160(1),'MGVX160(R)=',MGVX160(2)
      write(*,4) 'MGVX161(L)=',MGVX161(1),'MGVX161(R)=',MGVX161(2)
      write(*,4) 'MGVX162(L)=',MGVX162(1),'MGVX162(R)=',MGVX162(2)
      write(*,4) 'MGVX163(L)=',MGVX163(1),'MGVX163(R)=',MGVX163(2)
      write(*,4) 'MGVX164(L)=',MGVX164(1),'MGVX164(R)=',MGVX164(2)
      write(*,4) 'MGVX174(L)=',MGVX174(1),'MGVX174(R)=',MGVX174(2)
      write(*,4) 'MGVX175(L)=',MGVX175(1),'MGVX175(R)=',MGVX175(2)
      write(*,4) 'MGVX176(L)=',MGVX176(1),'MGVX176(R)=',MGVX176(2)
      write(*,4) 'MGVX186(L)=',MGVX186(1),'MGVX186(R)=',MGVX186(2)
      write(*,4) 'MGVX187(L)=',MGVX187(1),'MGVX187(R)=',MGVX187(2)
      write(*,4) 'MGVX188(L)=',MGVX188(1),'MGVX188(R)=',MGVX188(2)
      write(*,4) 'MGVX189(L)=',MGVX189(1),'MGVX189(R)=',MGVX189(2)
      write(*,4) 'MGVX190(L)=',MGVX190(1),'MGVX190(R)=',MGVX190(2)
      write(*,4) 'MGVX191(L)=',MGVX191(1),'MGVX191(R)=',MGVX191(2)
      write(*,4) 'MGVX192(L)=',MGVX192(1),'MGVX192(R)=',MGVX192(2)
      write(*,4) 'MGVX193(L)=',MGVX193(1),'MGVX193(R)=',MGVX193(2)
      write(*,4) 'MGVX194(L)=',MGVX194(1),'MGVX194(R)=',MGVX194(2)
      write(*,4) 'MGVX195(L)=',MGVX195(1),'MGVX195(R)=',MGVX195(2)
      write(*,4) 'MGVX198(L)=',MGVX198(1),'MGVX198(R)=',MGVX198(2)
      write(*,4) 'MGVX204(L)=',MGVX204(1),'MGVX204(R)=',MGVX204(2)
      write(*,4) 'MGVX201(L)=',MGVX201(1),'MGVX201(R)=',MGVX201(2)
      write(*,4) 'MGVX66(L)=',MGVX66(1),'MGVX66(R)=',MGVX66(2)
      write(*,4) 'MGVX57(L)=',MGVX57(1),'MGVX57(R)=',MGVX57(2)
      write(*,4) 'GG(L)=',GG(1),'GG(R)=',GG(2)
      write(*,4) 'MGVX111(L)=',MGVX111(1),'MGVX111(R)=',MGVX111(2)
      write(*,4) 'MGVX297(L)=',MGVX297(1),'MGVX297(R)=',MGVX297(2)
      write(*,*)  ' '
      write(*,*)  ' '
