c This file has been generated automatically by FeynRules
c Version: 1.4.0   Date: 15. 7. 2009,    16:23

c External Parameters :
      double precision cabi,s12,s23,s13,amass,R,LR,aEWM1,Gf,aS,ZM,s
     +w,ymc,ymb,ymt,ymtau,y1,y2,y3,y4,y5
      common/external_params/ cabi,s12,s23,s13,amass,R,LR,aEWM1,Gf,
     +aS,ZM,sw,ymc,ymb,ymt,ymtau,y1,y2,y3,y4,y5

c Internal Parameters :
      double precision aEW,sw2,cw,ee,gw,g1,v,lam,muH,ytau,yc,yt,yb,
     +c12,c23,c13,gmass,mn,mQ2,mu2,md2,mL2,me2,mQt,mt0,cH2,MM11,MM
     +12,MM22,Delta,Sqrt2,SqrtPi,Pgw2,Psw2,Pcw2,GGT1,G1G1T2
      common/internal_params_R/ aEW,sw2,cw,ee,gw,g1,v,lam,muH,ytau,
     +yc,yt,yb,c12,c23,c13,gmass,mn,mQ2,mu2,md2,mL2,me2,mQt,mt0,cH
     +2,MM11,MM12,MM22,Delta,Sqrt2,SqrtPi,Pgw2,Psw2,Pcw2,GGT1,G1G1
     +T2
      double complex CKM11,CKM12,CKM13,CKM21,CKM22,CKM23,CKM31,CKM3
     +2,CKM33,YukD11,YukD12,YukD13,YukD21,YukD22,YukD23,YukD31,Yuk
     +D32,YukD33,CONJCKM23,CONJCKM33,CONJCKM13,CONJCKM21,CONJCKM31
     +,CONJCKM11,CONJCKM22,CONJCKM32,CONJCKM12
      common/internal_params_C/ CKM11,CKM12,CKM13,CKM21,CKM22,CKM23
     +,CKM31,CKM32,CKM33,YukD11,YukD12,YukD13,YukD21,YukD22,YukD23
     +,YukD31,YukD32,YukD33,CONJCKM23,CONJCKM33,CONJCKM13,CONJCKM2
     +1,CONJCKM31,CONJCKM11,CONJCKM22,CONJCKM32,CONJCKM12
