      call LHA_get_real(npara,param,value,"cabi",cabi,"4.8800000000"
     +//"000E-01")
      call LHA_get_real(npara,param,value,"s12",s12,"2.210000000000"
     +//"0E-01")
      call LHA_get_real(npara,param,value,"s23",s23,"4.100000000000"
     +//"0E-02")
      call LHA_get_real(npara,param,value,"s13",s13,"3.500000000000"
     +//"0E-03")
      call LHA_get_real(npara,param,value,"amass",amass,"1.17200000"
     +//"00000E-01")
      call LHA_get_real(npara,param,value,"R",R,"2.0000000000000E-0"
     +//"3")
      call LHA_get_real(npara,param,value,"LR",LR,"2.0000000000000E"
     +//"+01")
      call LHA_get_real(npara,param,value,"aEWM1",aEWM1,"1.28000000"
     +//"00000E+02")
      call LHA_get_real(npara,param,value,"Gf",Gf,"1.1663900000000E"
     +//"-05")
      call LHA_get_real(npara,param,value,"aS",aS,"1.1720000000000E"
     +//"-01")
      call LHA_get_real(npara,param,value,"ZM",ZM,"9.1187600000000E"
     +//"+01")
      call LHA_get_real(npara,param,value,"sw",sw,"4.8076000000000E"
     +//"-01")
      call LHA_get_real(npara,param,value,"ymc",ymc,"1.420000000000"
     +//"0E+00")
      call LHA_get_real(npara,param,value,"ymb",ymb,"4.200000000000"
     +//"0E+00")
      call LHA_get_real(npara,param,value,"ymt",ymt,"1.750000000000"
     +//"0E+02")
      call LHA_get_real(npara,param,value,"ymtau",ymtau,"1.77700000"
     +//"00000E+00")
      call LHA_get_real(npara,param,value,"y1",y1,"-1.000000000000E"
     +//"+00")
      call LHA_get_real(npara,param,value,"y2",y2,"-2.000000000000E"
     +//"+00")
      call LHA_get_real(npara,param,value,"y3",y3,"3.3333333333333E"
     +//"-01")
      call LHA_get_real(npara,param,value,"y4",y4,"1.3333333333333E"
     +//"+00")
      call LHA_get_real(npara,param,value,"y5",y5,"-6.666666666666E"
     +//"-01")
      call LHA_get_real(npara,param,value,"MD",MD,"7.0000000000000E"
     +//"-03")
      call LHA_get_real(npara,param,value,"MU",MU,"3.0000000000000E"
     +//"-03")
      call LHA_get_real(npara,param,value,"MS",MS,"2.0000000000000E"
     +//"-01")
      call LHA_get_real(npara,param,value,"MC",MC,"1.4200000000000E"
     +//"+00")
      call LHA_get_real(npara,param,value,"MB",MB,"4.2000000000000E"
     +//"+00")
      call LHA_get_real(npara,param,value,"MT",MT,"1.7500000000000E"
     +//"+02")
      call LHA_get_real(npara,param,value,"MM",MM,"1.0570000000000E"
     +//"-01")
      call LHA_get_real(npara,param,value,"MTA",MTA,"1.770000000000"
     +//"0E+00")
      call LHA_get_real(npara,param,value,"MZ",MZ,"9.1187600000000E"
     +//"+01")
      call LHA_get_real(npara,param,value,"MW",MW,"7.9958049843868E"
     +//"+01")
      call LHA_get_real(npara,param,value,"MH",MH,"1.2000000000000E"
     +//"+02")
      call LHA_get_real(npara,param,value,"DMd",DMd,"5.975681544571"
     +//"5E+02")
      call LHA_get_real(npara,param,value,"DMu",DMu,"5.975681544571"
     +//"5E+02")
      call LHA_get_real(npara,param,value,"DMs",DMs,"5.975681544571"
     +//"5E+02")
      call LHA_get_real(npara,param,value,"DMc",DMc,"5.975681544571"
     +//"5E+02")
      call LHA_get_real(npara,param,value,"DMb",DMb,"5.831085659459"
     +//"7E+02")
      call LHA_get_real(npara,param,value,"DMtop",DMtop,"5.83542517"
     +//"88890E+02")
      call LHA_get_real(npara,param,value,"DMe",DMe,"5.149604028106"
     +//"5E+02")
      call LHA_get_real(npara,param,value,"DMn1",DMn1,"5.1496040281"
     +//"065E+02")
      call LHA_get_real(npara,param,value,"DMmu",DMmu,"5.1496040281"
     +//"065E+02")
      call LHA_get_real(npara,param,value,"DMn2",DMn2,"5.1496040281"
     +//"065E+02")
      call LHA_get_real(npara,param,value,"DMtau",DMtau,"5.14960402"
     +//"81065E+02")
      call LHA_get_real(npara,param,value,"DMn3",DMn3,"5.1496040281"
     +//"065E+02")
      call LHA_get_real(npara,param,value,"MG1",MG1,"6.404896105996"
     +//"8E+02")
      call LHA_get_real(npara,param,value,"MB1",MB1,"5.008931346083"
     +//"3E+02")
      call LHA_get_real(npara,param,value,"MZ1",MZ1,"5.354922830388"
     +//"2E+02")
      call LHA_get_real(npara,param,value,"MW1",MW1,"5.351691177605"
     +//"2E+02")
      call LHA_get_real(npara,param,value,"MH1",MH1,"4.901868723803"
     +//"7E+02")
      call LHA_get_real(npara,param,value,"SMd",SMd,"5.844244867691"
     +//"2E+02")
      call LHA_get_real(npara,param,value,"SMu",SMu,"5.862412218917"
     +//"5E+02")
      call LHA_get_real(npara,param,value,"SMs",SMs,"5.844244867691"
     +//"2E+02")
      call LHA_get_real(npara,param,value,"SMc",SMc,"5.862412218917"
     +//"5E+02")
      call LHA_get_real(npara,param,value,"SMb",SMb,"5.844395955490"
     +//"9E+02")
      call LHA_get_real(npara,param,value,"SMtop",SMtop,"6.09344147"
     +//"74544E+02")
      call LHA_get_real(npara,param,value,"SMe",SMe,"5.054502053678"
     +//"8E+02")
      call LHA_get_real(npara,param,value,"SMmu",SMmu,"5.0545020536"
     +//"788E+02")
      call LHA_get_real(npara,param,value,"SMtau",SMtau,"5.05450205"
     +//"36788E+02")
      call LHA_get_real(npara,param,value,"WT",WT,"1.5900000000000E"
     +//"+00")
      call LHA_get_real(npara,param,value,"WZ",WZ,"2.4944400000000E"
     +//"+00")
      call LHA_get_real(npara,param,value,"WW",WW,"2.0889500000000E"
     +//"+00")
      call LHA_get_real(npara,param,value,"WH",WH,"4.2440000000000E"
     +//"-03")
      call LHA_get_real(npara,param,value,"DWd",DWd,"2.512000000000"
     +//"0E-01")
      call LHA_get_real(npara,param,value,"DWu",DWu,"2.512000000000"
     +//"0E-01")
      call LHA_get_real(npara,param,value,"DWs",DWs,"2.510100000000"
     +//"0E-01")
      call LHA_get_real(npara,param,value,"DWc",DWc,"2.512000000000"
     +//"0E-01")
      call LHA_get_real(npara,param,value,"DWb",DWb,"5.404100000000"
     +//"0E-02")
      call LHA_get_real(npara,param,value,"DWtop",DWtop,"1.00960000"
     +//"00000E-01")
      call LHA_get_real(npara,param,value,"DWe",DWe,"1.463000000000"
     +//"0E-03")
      call LHA_get_real(npara,param,value,"DWn1",DWn1,"1.4630000000"
     +//"000E-03")
      call LHA_get_real(npara,param,value,"DWmu",DWmu,"1.4630000000"
     +//"000E-03")
      call LHA_get_real(npara,param,value,"DWn2",DWn2,"1.4630000000"
     +//"000E-03")
      call LHA_get_real(npara,param,value,"DWtau",DWtau,"1.46300000"
     +//"00000E-03")
      call LHA_get_real(npara,param,value,"DWn3",DWn3,"1.4630000000"
     +//"000E-03")
      call LHA_get_real(npara,param,value,"WG1",WG1,"4.207153000000"
     +//"0E+00")
      call LHA_get_real(npara,param,value,"WZ1",WZ1,"7.567860000000"
     +//"0E-02")
      call LHA_get_real(npara,param,value,"WW1",WW1,"7.345485000000"
     +//"0E-02")
      call LHA_get_real(npara,param,value,"WH1",WH1,"4.244000000000"
     +//"0E-03")
      call LHA_get_real(npara,param,value,"SWd",SWd,"1.981500000000"
     +//"0E-02")
      call LHA_get_real(npara,param,value,"SWu",SWu,"8.217900000000"
     +//"0E-02")
      call LHA_get_real(npara,param,value,"SWs",SWs,"1.975400000000"
     +//"0E-02")
      call LHA_get_real(npara,param,value,"SWc",SWc,"8.217900000000"
     +//"0E-02")
      call LHA_get_real(npara,param,value,"SWb",SWb,"1.976100000000"
     +//"0E-02")
      call LHA_get_real(npara,param,value,"SWe",SWe,"6.229100000000"
     +//"0E-04")
      call LHA_get_real(npara,param,value,"SWmu",SWmu,"6.2291000000"
     +//"000E-05")
      call LHA_get_real(npara,param,value,"SWtau",SWtau,"6.22910000"
     +//"00000E-04")
