c      Input values....
      common /USR_PARAM/ s0scalarf  ,s0axialf   ,s1quleft   ,s1quright  ,s1qdleft   ,s1qdright  ,s1eleft 
     & ,s1eright   ,s1ne      ,o1quleft   ,o1quright  ,o1qdleft   ,o1qdright  ,kapMpl ,addn,mstring    
     & ,s1muleft,s1muright,s1taleft,s1taright,s1qsleft,s1qcleft,s1qbleft,s1qtleft
     & ,s1qsright,s1qcright,s1qbright,s1qtright,o1qsleft,o1qsright,o1qcleft,o1qcright,o1qbleft,o1qbright
     & ,o1qtleft,o1qtright,s1nm,s1nt,o0scalarf,o0axialf
