      call LHA_get_real(npara,param,value,"aEWM1",aEWM1,"1.27900000"
     +//"00000E+02")
      call LHA_get_real(npara,param,value,"Gf",Gf,"1.1663700000000E"
     +//"-05")
      call LHA_get_real(npara,param,value,"aS",aS,"1.1720000000000E"
     +//"-01")
      call LHA_get_real(npara,param,value,"ZM",ZM,"9.1187600000000E"
     +//"+01")
      call LHA_get_real(npara,param,value,"MF",MF,"4.0000000000000E"
     +//"+03")
      call LHA_get_real(npara,param,value,"mst",mst,"1.040000000000"
     +//"0E-01")
      call LHA_get_real(npara,param,value,"mch",mch,"1.270000000000"
     +//"0E+00")
      call LHA_get_real(npara,param,value,"mbo",mbo,"4.200000000000"
     +//"0E+00")
      call LHA_get_real(npara,param,value,"mto",mto,"1.712000000000"
     +//"0E+02")
      call LHA_get_real(npara,param,value,"mmu",mmu,"1.057000000000"
     +//"0E-01")
      call LHA_get_real(npara,param,value,"mta",mta,"1.777000000000"
     +//"0E+00")
      call LHA_get_real(npara,param,value,"MZ",MZ,"9.1187600000000E"
     +//"+01")
      call LHA_get_real(npara,param,value,"MW",MW,"8.0398000000000E"
     +//"+01")
      call LHA_get_real(npara,param,value,"MhDo",MhDo,"4.1107611855"
     +//"009E+03")
      call LHA_get_real(npara,param,value,"MhUp",MhUp,"4.1107611855"
     +//"009E+03")
      call LHA_get_real(npara,param,value,"MhSt",MhSt,"4.1107612089"
     +//"316E+03")
      call LHA_get_real(npara,param,value,"MhCh",MhCh,"4.1107646795"
     +//"304E+03")
      call LHA_get_real(npara,param,value,"MhBo",MhBo,"4.1107993995"
     +//"995E+03")
      call LHA_get_real(npara,param,value,"MhTo",MhTo,"4.1758798031"
     +//"941E+03")
      call LHA_get_real(npara,param,value,"MhEl",MhEl,"4.1107611855"
     +//"009E+03")
      call LHA_get_real(npara,param,value,"MhMu",MhMu,"4.1107612097"
     +//"039E+03")
      call LHA_get_real(npara,param,value,"MhTa",MhTa,"4.1107680261"
     +//"065E+03")
      call LHA_get_real(npara,param,value,"MZP",MZP,"5.016811809292"
     +//"6E+02")
      call LHA_get_real(npara,param,value,"MWP",MWP,"5.000000000000"
     +//"0E+02")
      call LHA_get_real(npara,param,value,"MhNuMG1",MhNuMG1,"4.1107"
     +//"611855009E+03")
      call LHA_get_real(npara,param,value,"MhNuMG2",MhNuMG2,"4.1107"
     +//"611855009E+03")
      call LHA_get_real(npara,param,value,"MhNuMG3",MhNuMG3,"4.1107"
     +//"611855009E+03")
      call LHA_get_real(npara,param,value,"wto",wto,"1.508336490000"
     +//"0E+00")
      call LHA_get_real(npara,param,value,"WZ",WZ,"2.4952000000000E"
     +//"+00")
      call LHA_get_real(npara,param,value,"WW",WW,"2.1410000000000E"
     +//"+00")
      call LHA_get_real(npara,param,value,"WhDo",WhDo,"1.0000000000"
     +//"000E+00")
      call LHA_get_real(npara,param,value,"WhUp",WhUp,"1.0000000000"
     +//"000E+00")
      call LHA_get_real(npara,param,value,"WhSt",WhSt,"1.0000000000"
     +//"000E+00")
      call LHA_get_real(npara,param,value,"WhCh",WhCh,"1.0000000000"
     +//"000E+00")
      call LHA_get_real(npara,param,value,"WhBo",WhBo,"1.0000000000"
     +//"000E+00")
      call LHA_get_real(npara,param,value,"WhTo",WhTo,"1.0000000000"
     +//"000E+00")
      call LHA_get_real(npara,param,value,"WhEl",WhEl,"1.0000000000"
     +//"000E+00")
      call LHA_get_real(npara,param,value,"WhNu1",WhNu1,"1.00000000"
     +//"00000E+00")
      call LHA_get_real(npara,param,value,"WhMu",WhMu,"1.0000000000"
     +//"000E+00")
      call LHA_get_real(npara,param,value,"WhNu2",WhNu2,"1.00000000"
     +//"00000E+00")
      call LHA_get_real(npara,param,value,"WhTa",WhTa,"1.0000000000"
     +//"000E+00")
      call LHA_get_real(npara,param,value,"WhNu3",WhNu3,"1.00000000"
     +//"00000E+00")
      call LHA_get_real(npara,param,value,"WZP",WZP,"5.000000000000"
     +//"0E+00")
      call LHA_get_real(npara,param,value,"WWP",WWP,"5.000000000000"
     +//"0E+00")
