###########################################################
##							 ##
##		ordering width information		 ##
##		**************************		 ##
##							 ##
##	Authors: Pierre Artoisenet (UCL-CP3)		 ##
##	         Olivier Mattelaer (UCL-CP3)		 ##
##							 ##
###########################################################
##    file generated automatically                       ##
##	Transfer functions type : TF_on_leptons		 ##
###########################################################
## TAG         VALUE
  DELTA        j,b,g  	
  THIN 	       m,e
  LARGE        a,t
   X                0
