(* Code automatically generated by 'PreSARAH' *) 
(* Expressions for amplitudes are obtained by FeynArts/FormCalc *) 
(* This file is supposed to be loaded and used by SARAH *) 
(* Created at 15:49 on 31.3.2014 *) 
 
 
PrintDebug["   ... ",Gamma2l]; 
NamesParticles =  {bar[ChargedLepton], ChargedLepton, Photon}; 
 NamesOperators =  {OA2lSL, OA2lSR, OA1L, OA1R}; 
 NameProcess = Gamma2l; 
 
Generate[Gamma2l][file_]:=Block[{i,j,k}, 
 

 (* Creating all possible processes; extract information about involved masses/couplings *) 


(* ------------------------------- *)
(* {bar[ChargedLepton], ChargedLepton, Photon} *)
(* ------------------------------- *)
 
GetInformtion2Fermion1BosonProcess[bar[ChargedLepton],ChargedLepton,Photon,Gamma2l,file]; 
NeededMassesAll=Intersection[NeededMasses];
NeededCouplingsAll=Intersection[NeededCouplings];
WriteCodeObservablePreSARAH[Gamma2l][NeededMassesAll,NeededCouplingsAll,TreeContributions,WaveContributions,PenguinContributions,file]; 
NeededMassAllSaved[Gamma2l] = masses 
]; 

WriteCodeObservablePreSARAH[Gamma2l][masses_,couplings_,tree_,wave_,penguin_,file_] :=Block[{i,j,k,fermions,scalars}, 
 
NeededMassesAllSaved[Gamma2l] = masses; 
NeededCouplingsAllSaved[Gamma2l] = couplings; 
NeededCombinations[Gamma2l] = {{2, 1}, {3, 1}, {3, 2}}; 
PrintDebug["     writing SPheno code for ",Gamma2l]; 
MakeSubroutineTitle["CalculateGamma2l",Flatten[{masses,couplings}],{"gt1","gt2","gt3","OnlySM"}, 
{"OA2lSL", "OA2lSR", "OA1L", "OA1R"},file]; 
WriteString[file,"! ---------------------------------------------------------------- \n"]; 
WriteString[file,"! Code based on automatically generated SARAH extensions by 'PreSARAH' \n"]; 
WriteString[file,"! Expressions for amplitudes are obtained by FeynArts/FormCalc \n"]; 
WriteString[file,"! Based on user input for process Gamma2l \n"]; 
WriteString[file,"! 'PreSARAH' output has been generated  at 15:49 on 31.3.2014 \n"]; 
WriteString[file,"! ---------------------------------------------------------------- \n \n"]; 
 
 
WriteString[file,"Implicit None \n"]; 
MakeVariableList[Flatten[{couplings,masses}],",Intent(in)",file];
WriteString[file,"Integer,Intent(in) :: gt1, gt2,gt3 \n"];
WriteString[file,"Integer :: gt4 \n"];
WriteString[file,"Logical, Intent(in) :: OnlySM \n"];
WriteString[file,"Integer :: iprop, i1, i2, i3, i4 \n"];
WriteString[file,"Real(dp) :: MassEx1,MassEx2,MassEx3,MassEx12,MassEx22,MassEx32 \n"];
WriteString[file,"Complex(dp), Intent(out) :: OA2lSL \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: OA2lSR \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: OA1L \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: OA1R \n"]; 
WriteString[file,"Real(dp) ::  MP, MP2, IMP2, IMP, MFin, MFin2, IMFin, IMFin2, Finite  \n"];
WriteString[file,"Real(dp) ::  MS1, MS12, MS2, MS22, MF1, MF12, MF2, MF22, MV1, MV12, MV2, MV22  \n"];
WriteString[file,"Complex(dp) ::  chargefactor  \n"];
WriteString[file,"Complex(dp) ::  coup1L, coup1R, coup2L, coup2R, coup3L, coup3R, coup3, coup4L, coup4R \n\n"];

WriteString[file,"Complex(dp) ::  int1,int2,int3,int4,int5,int6,int7,int8 \n\n"];

WriteString[file,"Iname=Iname+1 \n"];
WriteString[file,"NameOfUnit(Iname)='CalculateGamma2l' \n
"];
 
AddCalcSquaredMasses[masses,file]; 
(* Initaliziation *)
WriteString[file,"Finite=1._dp \n"];
WriteString[file,"MassEx1="<>SPhenoMass[bar[ChargedLepton],gt1]<>"  \n"];
WriteString[file,"MassEx12="<>SPhenoMassSq[bar[ChargedLepton],gt1]<>" \n"];
WriteString[file,"MassEx2="<>SPhenoMass[ChargedLepton,gt2]<>"  \n"];
WriteString[file,"MassEx22="<>SPhenoMassSq[ChargedLepton,gt2]<>" \n"];
WriteString[file,"MassEx3="<>SPhenoMass[Photon,gt3]<>"  \n"];
WriteString[file,"MassEx32="<>SPhenoMassSq[Photon,gt3]<>" \n"];
WriteString[file,"! ------------------------------ \n "];
WriteString[file,"! Amplitudes for external states \n "];
WriteString[file,"! {bar[ChargedLepton], ChargedLepton, Photon} \n "];
WriteString[file,"! ------------------------------ \n \n"];
WriteString[sphenoTeX,"\\section{External states: $"<>TeXOutput[{bar[ChargedLepton][{gt1}], ChargedLepton[{gt2}], Photon[{gt3}]}]<>"$} \n"];
WriteString[file,"OA2lSL=0._dp \n"]; 
WriteString[file,"OA2lSR=0._dp \n"]; 
WriteString[file,"OA1L=0._dp \n"]; 
WriteString[file,"OA1R=0._dp \n"]; 
WriteDiagramsObservable[Gamma2l,tree, wave, penguin, file];
WriteString[file,"OA2lSL=oo16pi2*OA2lSL \n"]; 
WriteString[file,"OA2lSR=oo16pi2*OA2lSR \n"]; 
WriteString[file,"OA1L=oo16pi2*OA1L \n"]; 
WriteString[file,"OA1R=oo16pi2*OA1R \n"]; 
WriteString[file,"Iname=Iname-1\n\n"]; 
WriteString[file,"End Subroutine CalculateGamma2l \n\n"]; 
]; 
AddTreeResultPreSARAH[Gamma2l][top_,type_,file_]:=Block[{}, 

 (* This routine returns the generic expression for the amplitude of a given triangle diagram *) 
 
 Switch[top,  (* Check topology *) 
  1, 
	 	 WriteString[file,"  OA2lSL=OA2lSL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  OA2lSL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[file,"  OA2lSR=OA2lSR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  OA2lSR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[file,"  OA1L=OA1L+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  OA1L= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[file,"  OA1R=OA1R+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  OA1R= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
]; 
]; 


AddPenguinResultPreSARAH[Gamma2l][top_,type_,file_]:=Block[{}, 

 (* This routine returns the generic expression for the amplitude of a given triangle diagram *) 
 
 Switch[top,  (* Check topology *) 
  1, 
  Switch[type,  (* Check the generic type of the diagram *) 
	SFF, 
	 	 WriteString[file,"  int1=C0m(mF22, mF12, mS12)\n" ];
	 	 WriteString[sphenoTeX,"I_1= & "<> StringReplace["C0m(mF22, mF12, mS12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=C12m(mF22, mF12, mS12)\n" ];
	 	 WriteString[sphenoTeX,"I_2= & "<> StringReplace["C12m(mF22, mF12, mS12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int3=C1m(mF22, mF12, mS12)\n" ];
	 	 WriteString[sphenoTeX,"I_3= & "<> StringReplace["C1m(mF22, mF12, mS12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int4=C22m(mF22, mF12, mS12)\n" ];
	 	 WriteString[sphenoTeX,"I_4= & "<> StringReplace["C22m(mF22, mF12, mS12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int5=C2m(mF22, mF12, mS12)\n" ];
	 	 WriteString[sphenoTeX,"I_5= & "<> StringReplace["C2m(mF22, mF12, mS12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  OA2lSL=OA2lSL+2.*chargefactor*(coup1L*coup2R*coup3R*int2*MassEx1 - 1.*coup1R*(coup2L*coup3L*(int2 + int4 + int5)*MassEx2 + coup2R*(coup3R*int3*mF1 - 1.*coup3L*(int1 + int3 + int5)*mF2)))\n" ];
	 	 WriteString[sphenoTeX,"  OA2lSL= & "<> StringReplace["2 chargefactor (coup1L coup2R coup3R I_2 MassEx1 - coup1R (coup2L coup3L (I_2 + I_4 + I_5) MassEx2 + coup2R (coup3R I_3 mF1 - coup3L (I_1 + I_3 + I_5) mF2)))",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  OA2lSR=OA2lSR+2.*chargefactor*(coup1R*coup2L*coup3L*int2*MassEx1 - 1.*coup1L*(coup2R*coup3R*(int2 + int4 + int5)*MassEx2 + coup2L*(coup3L*int3*mF1 - 1.*coup3R*(int1 + int3 + int5)*mF2)))\n" ];
	 	 WriteString[sphenoTeX,"  OA2lSR= & "<> StringReplace["2 chargefactor (coup1R coup2L coup3L I_2 MassEx1 - coup1L (coup2R coup3R (I_2 + I_4 + I_5) MassEx2 + coup2L (coup3L I_3 mF1 - coup3R (I_1 + I_3 + I_5) mF2)))",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  OA1L=OA1L+chargefactor*coup1R*coup2L*coup3L*MonopoleSFF(mS12, mF12, mF22)\n" ];
	 	 WriteString[sphenoTeX,"  OA1L= & "<> StringReplace["chargefactor coup1R coup2L coup3L MonopoleSFF(mS12, mF12, mF22)",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  OA1R=OA1R+chargefactor*coup1L*coup2R*coup3L*MonopoleSFF(mS12, mF12, mF22)\n" ];
	 	 WriteString[sphenoTeX,"  OA1R= & "<> StringReplace["chargefactor coup1L coup2R coup3L MonopoleSFF(mS12, mF12, mF22)",SA`SPhenoTeXSub]<>" \\\\ \n" ];
,
	FSS, 
	 	 WriteString[file,"  int1=C0m(mF12, mS22, mS12)\n" ];
	 	 WriteString[sphenoTeX,"I_1= & "<> StringReplace["C0m(mF12, mS22, mS12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=C11m(mF12, mS22, mS12)\n" ];
	 	 WriteString[sphenoTeX,"I_2= & "<> StringReplace["C11m(mF12, mS22, mS12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int3=C12m(mF12, mS22, mS12)\n" ];
	 	 WriteString[sphenoTeX,"I_3= & "<> StringReplace["C12m(mF12, mS22, mS12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int4=C1m(mF12, mS22, mS12)\n" ];
	 	 WriteString[sphenoTeX,"I_4= & "<> StringReplace["C1m(mF12, mS22, mS12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int5=C22m(mF12, mS22, mS12)\n" ];
	 	 WriteString[sphenoTeX,"I_5= & "<> StringReplace["C22m(mF12, mS22, mS12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int6=C2m(mF12, mS22, mS12)\n" ];
	 	 WriteString[sphenoTeX,"I_6= & "<> StringReplace["C2m(mF12, mS22, mS12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  OA2lSL=OA2lSL+2.*chargefactor*coup3*(coup1L*coup2R*(int3 + int5 + int6)*MassEx1 + coup1R*(coup2L*(int2 + int3 + int4)*MassEx2 - 1.*coup2R*(int1 + int4 + int6)*mF1))\n" ];
	 	 WriteString[sphenoTeX,"  OA2lSL= & "<> StringReplace["2 chargefactor coup3 (coup1L coup2R (I_3 + I_5 + I_6) MassEx1 + coup1R (coup2L (I_2 + I_3 + I_4) MassEx2 - coup2R (I_1 + I_4 + I_6) mF1))",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  OA2lSR=OA2lSR+2.*chargefactor*coup3*(coup1R*coup2L*(int3 + int5 + int6)*MassEx1 + coup1L*(coup2R*(int2 + int3 + int4)*MassEx2 - 1.*coup2L*(int1 + int4 + int6)*mF1))\n" ];
	 	 WriteString[sphenoTeX,"  OA2lSR= & "<> StringReplace["2 chargefactor coup3 (coup1R coup2L (I_3 + I_5 + I_6) MassEx1 + coup1L (coup2R (I_2 + I_3 + I_4) MassEx2 - coup2L (I_1 + I_4 + I_6) mF1))",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  OA1L=OA1L+-1.*chargefactor*coup1R*coup2L*coup3*MonopoleFSS(mF12, mS12, mS22)\n" ];
	 	 WriteString[sphenoTeX,"  OA1L= & "<> StringReplace["-(chargefactor coup1R coup2L coup3 MonopoleFSS(mF12, mS12, mS22))",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  OA1R=OA1R+-1.*chargefactor*coup1L*coup2R*coup3*MonopoleFSS(mF12, mS12, mS22)\n" ];
	 	 WriteString[sphenoTeX,"  OA1R= & "<> StringReplace["-(chargefactor coup1L coup2R coup3 MonopoleFSS(mF12, mS12, mS22))",SA`SPhenoTeXSub]<>" \\\\ \n" ];
,
	VFF, 
	 	 WriteString[file,"  int1=C12m(mF22, mF12, mV12)\n" ];
	 	 WriteString[sphenoTeX,"I_1= & "<> StringReplace["C12m(mF22, mF12, mV12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=C22m(mF22, mF12, mV12)\n" ];
	 	 WriteString[sphenoTeX,"I_2= & "<> StringReplace["C22m(mF22, mF12, mV12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int3=C2m(mF22, mF12, mV12)\n" ];
	 	 WriteString[sphenoTeX,"I_3= & "<> StringReplace["C2m(mF22, mF12, mV12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  OA2lSL=OA2lSL+-4.*chargefactor*(-1.*coup1L*coup2L*coup3L*(int1 + int3)*MassEx1 + coup1R*(coup2R*coup3R*(int1 + int2)*MassEx2 + coup2L*int3*(coup3L*mF1 + coup3R*mF2)))\n" ];
	 	 WriteString[sphenoTeX,"  OA2lSL= & "<> StringReplace["-4 chargefactor (-(coup1L coup2L coup3L (I_1 + I_3) MassEx1) + coup1R (coup2R coup3R (I_1 + I_2) MassEx2 + coup2L I_3 (coup3L mF1 + coup3R mF2)))",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  OA2lSR=OA2lSR+-4.*chargefactor*(-1.*coup1R*coup2R*coup3R*(int1 + int3)*MassEx1 + coup1L*(coup2L*coup3L*(int1 + int2)*MassEx2 + coup2R*int3*(coup3R*mF1 + coup3L*mF2)))\n" ];
	 	 WriteString[sphenoTeX,"  OA2lSR= & "<> StringReplace["-4 chargefactor (-(coup1R coup2R coup3R (I_1 + I_3) MassEx1) + coup1L (coup2L coup3L (I_1 + I_2) MassEx2 + coup2R I_3 (coup3R mF1 + coup3L mF2)))",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  OA1L=OA1L+-1.*chargefactor*coup1L*coup2L*coup3L*MonopoleVFF(mV12, mF12, mF22)\n" ];
	 	 WriteString[sphenoTeX,"  OA1L= & "<> StringReplace["-(chargefactor coup1L coup2L coup3L MonopoleVFF(mV12, mF12, mF22))",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  OA1R=OA1R+-1.*chargefactor*coup1R*coup2R*coup3L*MonopoleVFF(mV12, mF12, mF22)\n" ];
	 	 WriteString[sphenoTeX,"  OA1R= & "<> StringReplace["-(chargefactor coup1R coup2R coup3L MonopoleVFF(mV12, mF12, mF22))",SA`SPhenoTeXSub]<>" \\\\ \n" ];
,
	FSV, 
	 	 WriteString[file,"  int1=C1m(mF12, mV22, mS12)\n" ];
	 	 WriteString[sphenoTeX,"I_1= & "<> StringReplace["C1m(mF12, mV22, mS12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  OA2lSL=OA2lSL+-2.*chargefactor*coup1R*coup2L*coup3*int1\n" ];
	 	 WriteString[sphenoTeX,"  OA2lSL= & "<> StringReplace["-2 chargefactor coup1R coup2L coup3 I_1",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  OA2lSR=OA2lSR+-2.*chargefactor*coup1L*coup2R*coup3*int1\n" ];
	 	 WriteString[sphenoTeX,"  OA2lSR= & "<> StringReplace["-2 chargefactor coup1L coup2R coup3 I_1",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  OA1L=OA1L+-1.*chargefactor*coup1L*coup2R*coup3*MonopoleFSV(mF12, mS12, mV22)\n" ];
	 	 WriteString[sphenoTeX,"  OA1L= & "<> StringReplace["-(chargefactor coup1L coup2R coup3 MonopoleFSV(mF12, mS12, mV22))",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  OA1R=OA1R+-1.*chargefactor*coup1R*coup2L*coup3*MonopoleFSV(mF12, mS12, mV22)\n" ];
	 	 WriteString[sphenoTeX,"  OA1R= & "<> StringReplace["-(chargefactor coup1R coup2L coup3 MonopoleFSV(mF12, mS12, mV22))",SA`SPhenoTeXSub]<>" \\\\ \n" ];
,
	FVS, 
	 	 WriteString[file,"  int1=C2m(mF12, mS22, mV12)\n" ];
	 	 WriteString[sphenoTeX,"I_1= & "<> StringReplace["C2m(mF12, mS22, mV12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  OA2lSL=OA2lSL+-2.*chargefactor*coup1R*coup2R*coup3*int1\n" ];
	 	 WriteString[sphenoTeX,"  OA2lSL= & "<> StringReplace["-2 chargefactor coup1R coup2R coup3 I_1",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  OA2lSR=OA2lSR+-2.*chargefactor*coup1L*coup2L*coup3*int1\n" ];
	 	 WriteString[sphenoTeX,"  OA2lSR= & "<> StringReplace["-2 chargefactor coup1L coup2L coup3 I_1",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  OA1L=OA1L+-1.*chargefactor*coup1L*coup2L*coup3*MonopoleFVS(mF12, mV12, mS22)\n" ];
	 	 WriteString[sphenoTeX,"  OA1L= & "<> StringReplace["-(chargefactor coup1L coup2L coup3 MonopoleFVS(mF12, mV12, mS22))",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  OA1R=OA1R+-1.*chargefactor*coup1R*coup2R*coup3*MonopoleFVS(mF12, mV12, mS22)\n" ];
	 	 WriteString[sphenoTeX,"  OA1R= & "<> StringReplace["-(chargefactor coup1R coup2R coup3 MonopoleFVS(mF12, mV12, mS22))",SA`SPhenoTeXSub]<>" \\\\ \n" ];
,
	FVV, 
	 	 WriteString[file,"  int1=C11m(mF12, mV22, mV12)\n" ];
	 	 WriteString[sphenoTeX,"I_1= & "<> StringReplace["C11m(mF12, mV22, mV12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=C12m(mF12, mV22, mV12)\n" ];
	 	 WriteString[sphenoTeX,"I_2= & "<> StringReplace["C12m(mF12, mV22, mV12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int3=C1m(mF12, mV22, mV12)\n" ];
	 	 WriteString[sphenoTeX,"I_3= & "<> StringReplace["C1m(mF12, mV22, mV12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int4=C22m(mF12, mV22, mV12)\n" ];
	 	 WriteString[sphenoTeX,"I_4= & "<> StringReplace["C22m(mF12, mV22, mV12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int5=C2m(mF12, mV22, mV12)\n" ];
	 	 WriteString[sphenoTeX,"I_5= & "<> StringReplace["C2m(mF12, mV22, mV12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  OA2lSL=OA2lSL+2.*chargefactor*coup3*(coup1L*coup2L*(2.*int2 - 1.*int3 + 2.*int4)*MassEx1 + coup1R*(coup2R*(2.*int1 + 2.*int2 - 1.*int5)*MassEx2 + 3.*coup2L*(int3 + int5)*mF1))\n" ];
	 	 WriteString[sphenoTeX,"  OA2lSL= & "<> StringReplace["2 chargefactor coup3 (coup1L coup2L (2 I_2 - I_3 + 2 I_4) MassEx1 + coup1R (coup2R (2 I_1 + 2 I_2 - I_5) MassEx2 + 3 coup2L (I_3 + I_5) mF1))",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  OA2lSR=OA2lSR+2.*chargefactor*coup3*(coup1R*coup2R*(2.*int2 - 1.*int3 + 2.*int4)*MassEx1 + coup1L*(coup2L*(2.*int1 + 2.*int2 - 1.*int5)*MassEx2 + 3.*coup2R*(int3 + int5)*mF1))\n" ];
	 	 WriteString[sphenoTeX,"  OA2lSR= & "<> StringReplace["2 chargefactor coup3 (coup1R coup2R (2 I_2 - I_3 + 2 I_4) MassEx1 + coup1L (coup2L (2 I_1 + 2 I_2 - I_5) MassEx2 + 3 coup2R (I_3 + I_5) mF1))",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  OA1L=OA1L+-1.*chargefactor*coup1L*coup2L*coup3*MonopoleFVV(mF12, mV12, mV22)\n" ];
	 	 WriteString[sphenoTeX,"  OA1L= & "<> StringReplace["-(chargefactor coup1L coup2L coup3 MonopoleFVV(mF12, mV12, mV22))",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  OA1R=OA1R+-1.*chargefactor*coup1R*coup2R*coup3*MonopoleFVV(mF12, mV12, mV22)\n" ];
	 	 WriteString[sphenoTeX,"  OA1R= & "<> StringReplace["-(chargefactor coup1R coup2R coup3 MonopoleFVV(mF12, mV12, mV22))",SA`SPhenoTeXSub]<>" \\\\ \n" ];
]; 
];]; 


AddWaveResultPreSARAH[Gamma2l][top_,type_,file_]:=Block[{}, 

 (* This routine returns the generic expression for the amplitude of a given triangle diagram *) 
 
 Switch[top,  (* Check topology *) 
  1, 
  Switch[type,  (* Check the generic type of the diagram *) 
	FS | SF , 
	 	 WriteStringFLB[file,"  OA2lSL=OA2lSL+0.\n" ];
	 	 WriteString[sphenoTeX,"  OA2lSL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  OA2lSR=OA2lSR+0.\n" ];
	 	 WriteString[sphenoTeX,"  OA2lSR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  OA1L=OA1L+0.\n" ];
	 	 WriteString[sphenoTeX,"  OA1L= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  OA1R=OA1R+0.\n" ];
	 	 WriteString[sphenoTeX,"  OA1R= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
,
	FV | VF , 
	 	 WriteStringFLB[file,"  OA2lSL=OA2lSL+0.\n" ];
	 	 WriteString[sphenoTeX,"  OA2lSL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  OA2lSR=OA2lSR+0.\n" ];
	 	 WriteString[sphenoTeX,"  OA2lSR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  OA1L=OA1L+0.\n" ];
	 	 WriteString[sphenoTeX,"  OA1L= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  OA1R=OA1R+0.\n" ];
	 	 WriteString[sphenoTeX,"  OA1R= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
]; 
,
  2, 
  Switch[type,  (* Check the generic type of the diagram *) 
	FS | SF , 
	 	 WriteStringFLB[file,"  OA2lSL=OA2lSL+0.\n" ];
	 	 WriteString[sphenoTeX,"  OA2lSL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  OA2lSR=OA2lSR+0.\n" ];
	 	 WriteString[sphenoTeX,"  OA2lSR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  OA1L=OA1L+0.\n" ];
	 	 WriteString[sphenoTeX,"  OA1L= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  OA1R=OA1R+0.\n" ];
	 	 WriteString[sphenoTeX,"  OA1R= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
,
	FV | VF , 
	 	 WriteStringFLB[file,"  OA2lSL=OA2lSL+0.\n" ];
	 	 WriteString[sphenoTeX,"  OA2lSL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  OA2lSR=OA2lSR+0.\n" ];
	 	 WriteString[sphenoTeX,"  OA2lSR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  OA1L=OA1L+0.\n" ];
	 	 WriteString[sphenoTeX,"  OA1L= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  OA1R=OA1R+0.\n" ];
	 	 WriteString[sphenoTeX,"  OA1R= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
]; 
];]; 


