*
* $Id: mcbrat.inc,v 1.1 2009/06/08 19:12:57 madgraph Exp $
*
* $Log: mcbrat.inc,v $
* Revision 1.1  2009/06/08 19:12:57  madgraph
* Latest PGS and Pythia versions, allow ickkw=2
*
* Revision 1.1.1.1  1994/10/08  02:21:32  zfiles
* first version of qqlib in CVS
*
*
*CMZ :  1.04/00 21/09/94  22.54.46  by  Paul Avery
*-- Author :
*
*  >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
*                      MCBRAT.INC
*
*            Information on decay channels
*  >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
*
#include "qqlib/seq/qqbrat.inc"
