*
* $Id: mcmxcp.inc,v 1.1 2009/06/08 19:12:57 madgraph Exp $
*
* $Log: mcmxcp.inc,v $
* Revision 1.1  2009/06/08 19:12:57  madgraph
* Latest PGS and Pythia versions, allow ickkw=2
*
* Revision 1.1.1.1  1994/10/08  02:21:32  zfiles
* first version of qqlib in CVS
*
*
*CMZ :  1.04/00 21/09/94  22.55.21  by  Paul Avery
*-- Author :
*
*  >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
*                      MCMXCP.INC
*
*           Mixing and CP violation information
*  >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
*
#include "qqlib/seq/qqmxcp.inc"
