*
* $Id: qqbfld.inc,v 1.1 2009/06/08 19:12:57 madgraph Exp $
*
* $Log: qqbfld.inc,v $
* Revision 1.1  2009/06/08 19:12:57  madgraph
* Latest PGS and Pythia versions, allow ickkw=2
*
* Revision 1.1 1994/10/07 23:57:33 zfiles
* New include files for QQ.
*
*
*CMZ : 1.02/61 03/10/94 17.34.50 by Paul Avery
*CMZ : 08/10/93 16.07.05 by Paul Avery
*>> Author :
*
* >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
* QQBFLD.INC
*
* QQ B field
* >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
*
* BFLDQQ B field in KG (NOT Tesla)
      REAL BFLDQQ
      COMMON/QQBFL1/
     * BFLDQQ
