*
* $Id: qqwjet.inc,v 1.1 2009/06/08 19:12:58 madgraph Exp $
*
* $Log: qqwjet.inc,v $
* Revision 1.1  2009/06/08 19:12:58  madgraph
* Latest PGS and Pythia versions, allow ickkw=2
*
* Revision 1.1.1.1 1994/10/08 02:21:33 zfiles
* first version of qqlib in CVS
*
*
*CMZ : 1.04/00 21/09/94 22.55.57 by Paul Avery
*-- Author : Lynn Garren 06/12/93
*
* >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
* QQWJET.INC
*
* LOCAL VARIABLES THAT ARE USED IN SUBROUTINE WJET
* >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
*
      REAL BQMAS
      COMMON /WWJET/BQMAS(7)
C---------------------------------------------------------------------
