      call LHA_get_real(npara,param,value,"RRd11",RRd11,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRd12",RRd12,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRd13",RRd13,"9.38737896"
     +//"00000E-01")
      call LHA_get_real(npara,param,value,"RRd14",RRd14,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRd15",RRd15,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRd16",RRd16,"3.44631925"
     +//"00000E-01")
      call LHA_get_real(npara,param,value,"RRd21",RRd21,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRd22",RRd22,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRd23",RRd23,"-3.4463192"
     +//"50000E-01")
      call LHA_get_real(npara,param,value,"RRd24",RRd24,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRd25",RRd25,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRd26",RRd26,"9.38737896"
     +//"00000E-01")
      call LHA_get_real(npara,param,value,"RRd31",RRd31,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRd32",RRd32,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRd33",RRd33,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRd34",RRd34,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRd35",RRd35,"1.00000000"
     +//"00000E+00")
      call LHA_get_real(npara,param,value,"RRd36",RRd36,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRd41",RRd41,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRd42",RRd42,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRd43",RRd43,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRd44",RRd44,"1.00000000"
     +//"00000E+00")
      call LHA_get_real(npara,param,value,"RRd45",RRd45,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRd46",RRd46,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRd51",RRd51,"1.00000000"
     +//"00000E+00")
      call LHA_get_real(npara,param,value,"RRd52",RRd52,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRd53",RRd53,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRd54",RRd54,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRd55",RRd55,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRd56",RRd56,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRd61",RRd61,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRd62",RRd62,"1.00000000"
     +//"00000E+00")
      call LHA_get_real(npara,param,value,"RRd63",RRd63,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRd64",RRd64,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRd65",RRd65,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRd66",RRd66,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"alp",alp,"-1.13825210000"
     +//"0E-01")
      call LHA_get_real(npara,param,value,"yukd1",yukd1,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"yukd2",yukd2,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"yukd3",yukd3,"1.38840206"
     +//"00000E-01")
      call LHA_get_real(npara,param,value,"yukl1",yukl1,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"yukl2",yukl2,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"yukl3",yukl3,"1.00890810"
     +//"00000E-01")
      call LHA_get_real(npara,param,value,"yuku1",yuku1,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"yuku2",yuku2,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"yuku3",yuku3,"8.92844550"
     +//"00000E-01")
      call LHA_get_real(npara,param,value,"gp",gp,"3.6096684700000E"
     +//"-01")
      call LHA_get_real(npara,param,value,"gw",gw,"6.4648221000000E"
     +//"-01")
      call LHA_get_real(npara,param,value,"ggs",ggs,"1.101786790000"
     +//"0E+00")
      call LHA_get_real(npara,param,value,"RMU",RMU,"3.576809770000"
     +//"0E+02")
      call LHA_get_real(npara,param,value,"tb",tb,"9.7486240300000E"
     +//"+00")
      call LHA_get_real(npara,param,value,"vev",vev,"2.448945490000"
     +//"0E+02")
      call LHA_get_real(npara,param,value,"MA2",MA2,"1.664390650000"
     +//"0E+05")
      call LHA_get_real(npara,param,value,"IRd11",IRd11,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRd12",IRd12,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRd13",IRd13,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRd14",IRd14,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRd15",IRd15,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRd16",IRd16,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRd21",IRd21,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRd22",IRd22,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRd23",IRd23,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRd24",IRd24,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRd25",IRd25,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRd26",IRd26,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRd31",IRd31,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRd32",IRd32,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRd33",IRd33,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRd34",IRd34,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRd35",IRd35,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRd36",IRd36,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRd41",IRd41,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRd42",IRd42,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRd43",IRd43,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRd44",IRd44,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRd45",IRd45,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRd46",IRd46,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRd51",IRd51,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRd52",IRd52,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRd53",IRd53,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRd54",IRd54,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRd55",IRd55,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRd56",IRd56,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRd61",IRd61,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRd62",IRd62,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRd63",IRd63,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRd64",IRd64,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRd65",IRd65,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRd66",IRd66,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IMU",IMU,"0.00000000E+00"
     +//"")
      call LHA_get_real(npara,param,value,"ImDR11",ImDR11,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"ImDR12",ImDR12,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"ImDR13",ImDR13,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"ImDR21",ImDR21,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"ImDR22",ImDR22,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"ImDR23",ImDR23,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"ImDR31",ImDR31,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"ImDR32",ImDR32,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"ImDR33",ImDR33,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"ImER11",ImER11,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"ImER12",ImER12,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"ImER13",ImER13,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"ImER21",ImER21,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"ImER22",ImER22,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"ImER23",ImER23,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"ImER31",ImER31,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"ImER32",ImER32,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"ImER33",ImER33,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"ImLL11",ImLL11,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"ImLL12",ImLL12,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"ImLL13",ImLL13,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"ImLL21",ImLL21,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"ImLL22",ImLL22,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"ImLL23",ImLL23,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"ImLL31",ImLL31,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"ImLL32",ImLL32,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"ImLL33",ImLL33,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"IMx1",IMx1,"0.00000000E+"
     +//"00")
      call LHA_get_real(npara,param,value,"IMx2",IMx2,"0.00000000E+"
     +//"00")
      call LHA_get_real(npara,param,value,"IMx3",IMx3,"0.00000000E+"
     +//"00")
      call LHA_get_real(npara,param,value,"ImQL11",ImQL11,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"ImQL12",ImQL12,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"ImQL13",ImQL13,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"ImQL21",ImQL21,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"ImQL22",ImQL22,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"ImQL23",ImQL23,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"ImQL31",ImQL31,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"ImQL32",ImQL32,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"ImQL33",ImQL33,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"ImUR11",ImUR11,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"ImUR12",ImUR12,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"ImUR13",ImUR13,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"ImUR21",ImUR21,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"ImUR22",ImUR22,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"ImUR23",ImUR23,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"ImUR31",ImUR31,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"ImUR32",ImUR32,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"ImUR33",ImUR33,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"INN11",INN11,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"INN12",INN12,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"INN13",INN13,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"INN14",INN14,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"INN21",INN21,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"INN22",INN22,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"INN23",INN23,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"INN24",INN24,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"INN31",INN31,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"INN32",INN32,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"INN33",INN33,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"INN34",INN34,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"INN41",INN41,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"INN42",INN42,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"INN43",INN43,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"INN44",INN44,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRl11",IRl11,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRl12",IRl12,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRl13",IRl13,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRl14",IRl14,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRl15",IRl15,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRl16",IRl16,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRl21",IRl21,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRl22",IRl22,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRl23",IRl23,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRl24",IRl24,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRl25",IRl25,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRl26",IRl26,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRl31",IRl31,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRl32",IRl32,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRl33",IRl33,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRl34",IRl34,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRl35",IRl35,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRl36",IRl36,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRl41",IRl41,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRl42",IRl42,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRl43",IRl43,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRl44",IRl44,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRl45",IRl45,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRl46",IRl46,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRl51",IRl51,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRl52",IRl52,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRl53",IRl53,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRl54",IRl54,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRl55",IRl55,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRl56",IRl56,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRl61",IRl61,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRl62",IRl62,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRl63",IRl63,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRl64",IRl64,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRl65",IRl65,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRl66",IRl66,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRn11",IRn11,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRn12",IRn12,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRn13",IRn13,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRn21",IRn21,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRn22",IRn22,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRn23",IRn23,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRn31",IRn31,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRn32",IRn32,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRn33",IRn33,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Itd11",Itd11,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Itd12",Itd12,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Itd13",Itd13,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Itd21",Itd21,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Itd22",Itd22,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Itd23",Itd23,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Itd31",Itd31,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Itd32",Itd32,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Itd33",Itd33,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Ite11",Ite11,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Ite12",Ite12,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Ite13",Ite13,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Ite21",Ite21,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Ite22",Ite22,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Ite23",Ite23,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Ite31",Ite31,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Ite32",Ite32,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Ite33",Ite33,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Itu11",Itu11,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Itu12",Itu12,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Itu13",Itu13,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Itu21",Itu21,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Itu22",Itu22,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Itu23",Itu23,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Itu31",Itu31,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Itu32",Itu32,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Itu33",Itu33,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IUU11",IUU11,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IUU12",IUU12,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IUU21",IUU21,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IUU22",IUU22,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRu11",IRu11,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRu12",IRu12,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRu13",IRu13,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRu14",IRu14,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRu15",IRu15,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRu16",IRu16,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRu21",IRu21,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRu22",IRu22,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRu23",IRu23,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRu24",IRu24,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRu25",IRu25,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRu26",IRu26,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRu31",IRu31,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRu32",IRu32,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRu33",IRu33,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRu34",IRu34,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRu35",IRu35,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRu36",IRu36,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRu41",IRu41,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRu42",IRu42,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRu43",IRu43,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRu44",IRu44,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRu45",IRu45,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRu46",IRu46,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRu51",IRu51,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRu52",IRu52,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRu53",IRu53,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRu54",IRu54,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRu55",IRu55,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRu56",IRu56,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRu61",IRu61,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRu62",IRu62,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRu63",IRu63,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRu64",IRu64,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRu65",IRu65,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IRu66",IRu66,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"ICKM11",ICKM11,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"ICKM12",ICKM12,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"ICKM13",ICKM13,"-7.33935"
     +//"2310000E-02")
      call LHA_get_real(npara,param,value,"ICKM21",ICKM21,"-6.41808"
     +//"2620000E-03")
      call LHA_get_real(npara,param,value,"ICKM22",ICKM22,"-9.12695"
     +//"6350000E-03")
      call LHA_get_real(npara,param,value,"ICKM23",ICKM23,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"ICKM31",ICKM31,"-4.17265"
     +//"8540000E-02")
      call LHA_get_real(npara,param,value,"ICKM32",ICKM32,"-5.93380"
     +//"8370000E-02")
      call LHA_get_real(npara,param,value,"ICKM33",ICKM33,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"IVV11",IVV11,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IVV12",IVV12,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IVV21",IVV21,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"IVV22",IVV22,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RmDR11",RmDR11,"2.736846"
     +//"7400000E+05")
      call LHA_get_real(npara,param,value,"RmDR12",RmDR12,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"RmDR13",RmDR13,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"RmDR21",RmDR21,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"RmDR22",RmDR22,"2.736846"
     +//"7400000E+05")
      call LHA_get_real(npara,param,value,"RmDR23",RmDR23,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"RmDR31",RmDR31,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"RmDR32",RmDR32,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"RmDR33",RmDR33,"2.702619"
     +//"6900000E+05")
      call LHA_get_real(npara,param,value,"RmER11",RmER11,"1.863062"
     +//"8700000E+04")
      call LHA_get_real(npara,param,value,"RmER12",RmER12,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"RmER13",RmER13,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"RmER21",RmER21,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"RmER22",RmER22,"1.863062"
     +//"8700000E+04")
      call LHA_get_real(npara,param,value,"RmER23",RmER23,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"RmER31",RmER31,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"RmER32",RmER32,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"RmER33",RmER33,"1.796764"
     +//"0600000E+04")
      call LHA_get_real(npara,param,value,"RmLL11",RmLL11,"3.815567"
     +//"0000000E+04")
      call LHA_get_real(npara,param,value,"RmLL12",RmLL12,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"RmLL13",RmLL13,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"RmLL21",RmLL21,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"RmLL22",RmLL22,"3.815567"
     +//"0000000E+04")
      call LHA_get_real(npara,param,value,"RmLL23",RmLL23,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"RmLL31",RmLL31,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"RmLL32",RmLL32,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"RmLL33",RmLL33,"3.782867"
     +//"6900000E+04")
      call LHA_get_real(npara,param,value,"RMx1",RMx1,"1.0139653400"
     +//"000E+02")
      call LHA_get_real(npara,param,value,"RMx2",RMx2,"1.9150424100"
     +//"000E+02")
      call LHA_get_real(npara,param,value,"RMx3",RMx3,"5.8826303100"
     +//"000E+02")
      call LHA_get_real(npara,param,value,"MHu2",MHu2,"3.2337494300"
     +//"000E+04")
      call LHA_get_real(npara,param,value,"MHd2",MHd2,"-1.288001340"
     +//"000E+05")
      call LHA_get_real(npara,param,value,"RmQL11",RmQL11,"2.998367"
     +//"0100000E+05")
      call LHA_get_real(npara,param,value,"RmQL12",RmQL12,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"RmQL13",RmQL13,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"RmQL21",RmQL21,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"RmQL22",RmQL22,"2.998367"
     +//"0100000E+05")
      call LHA_get_real(npara,param,value,"RmQL23",RmQL23,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"RmQL31",RmQL31,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"RmQL32",RmQL32,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"RmQL33",RmQL33,"2.487653"
     +//"6700000E+05")
      call LHA_get_real(npara,param,value,"RmUR11",RmUR11,"2.803821"
     +//"0600000E+05")
      call LHA_get_real(npara,param,value,"RmUR12",RmUR12,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"RmUR13",RmUR13,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"RmUR21",RmUR21,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"RmUR22",RmUR22,"2.803821"
     +//"0600000E+05")
      call LHA_get_real(npara,param,value,"RmUR23",RmUR23,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"RmUR31",RmUR31,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"RmUR32",RmUR32,"0.000000"
     +//"00E+00")
      call LHA_get_real(npara,param,value,"RmUR33",RmUR33,"1.791370"
     +//"7200000E+05")
      call LHA_get_real(npara,param,value,"RNN11",RNN11,"9.86364430"
     +//"00000E-01")
      call LHA_get_real(npara,param,value,"RNN12",RNN12,"-5.3110355"
     +//"30000E-02")
      call LHA_get_real(npara,param,value,"RNN13",RNN13,"1.46433995"
     +//"00000E-01")
      call LHA_get_real(npara,param,value,"RNN14",RNN14,"-5.3118611"
     +//"70000E-02")
      call LHA_get_real(npara,param,value,"RNN21",RNN21,"9.93505358"
     +//"00000E-02")
      call LHA_get_real(npara,param,value,"RNN22",RNN22,"9.44949299"
     +//"00000E-01")
      call LHA_get_real(npara,param,value,"RNN23",RNN23,"-2.6984672"
     +//"00000E-01")
      call LHA_get_real(npara,param,value,"RNN24",RNN24,"1.56150698"
     +//"00000E-01")
      call LHA_get_real(npara,param,value,"RNN31",RNN31,"-6.0338800"
     +//"20000E-02")
      call LHA_get_real(npara,param,value,"RNN32",RNN32,"8.77004854"
     +//"00000E-02")
      call LHA_get_real(npara,param,value,"RNN33",RNN33,"6.95877493"
     +//"00000E-01")
      call LHA_get_real(npara,param,value,"RNN34",RNN34,"7.10226984"
     +//"00000E-01")
      call LHA_get_real(npara,param,value,"RNN41",RNN41,"-1.1650713"
     +//"20000E-01")
      call LHA_get_real(npara,param,value,"RNN42",RNN42,"3.10739017"
     +//"00000E-01")
      call LHA_get_real(npara,param,value,"RNN43",RNN43,"6.49225960"
     +//"00000E-01")
      call LHA_get_real(npara,param,value,"RNN44",RNN44,"-6.8437782"
     +//"30000E-01")
      call LHA_get_real(npara,param,value,"RRl11",RRl11,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRl12",RRl12,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRl13",RRl13,"2.82487190"
     +//"00000E-01")
      call LHA_get_real(npara,param,value,"RRl14",RRl14,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRl15",RRl15,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRl16",RRl16,"9.59271071"
     +//"00000E-01")
      call LHA_get_real(npara,param,value,"RRl21",RRl21,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRl22",RRl22,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRl23",RRl23,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRl24",RRl24,"1.00000000"
     +//"00000E+00")
      call LHA_get_real(npara,param,value,"RRl25",RRl25,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRl26",RRl26,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRl31",RRl31,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRl32",RRl32,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRl33",RRl33,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRl34",RRl34,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRl35",RRl35,"1.00000000"
     +//"00000E+00")
      call LHA_get_real(npara,param,value,"RRl36",RRl36,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRl41",RRl41,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRl42",RRl42,"1.00000000"
     +//"00000E+00")
      call LHA_get_real(npara,param,value,"RRl43",RRl43,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRl44",RRl44,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRl45",RRl45,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRl46",RRl46,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRl51",RRl51,"1.00000000"
     +//"00000E+00")
      call LHA_get_real(npara,param,value,"RRl52",RRl52,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRl53",RRl53,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRl54",RRl54,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRl55",RRl55,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRl56",RRl56,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRl61",RRl61,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRl62",RRl62,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRl63",RRl63,"9.59271071"
     +//"00000E-01")
      call LHA_get_real(npara,param,value,"RRl64",RRl64,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRl65",RRl65,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRl66",RRl66,"-2.8248719"
     +//"00000E-01")
      call LHA_get_real(npara,param,value,"aEWM1",aEWM1,"1.27934000"
     +//"00000E+02")
      call LHA_get_real(npara,param,value,"Gf",Gf,"1.1663700000000E"
     +//"-05")
      call LHA_get_real(npara,param,value,"aS",aS,"1.1800000000000E"
     +//"-01")
      call LHA_get_real(npara,param,value,"MMZ",MMZ,"9.118760000000"
     +//"0E+01")
      call LHA_get_real(npara,param,value,"RRn11",RRn11,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRn12",RRn12,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRn13",RRn13,"1.00000000"
     +//"00000E+00")
      call LHA_get_real(npara,param,value,"RRn21",RRn21,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRn22",RRn22,"1.00000000"
     +//"00000E+00")
      call LHA_get_real(npara,param,value,"RRn23",RRn23,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRn31",RRn31,"1.00000000"
     +//"00000E+00")
      call LHA_get_real(npara,param,value,"RRn32",RRn32,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRn33",RRn33,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Rtd11",Rtd11,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Rtd12",Rtd12,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Rtd13",Rtd13,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Rtd21",Rtd21,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Rtd22",Rtd22,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Rtd23",Rtd23,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Rtd31",Rtd31,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Rtd32",Rtd32,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Rtd33",Rtd33,"-1.1069374"
     +//"20000E+02")
      call LHA_get_real(npara,param,value,"Rte11",Rte11,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Rte12",Rte12,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Rte13",Rte13,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Rte21",Rte21,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Rte22",Rte22,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Rte23",Rte23,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Rte31",Rte31,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Rte32",Rte32,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Rte33",Rte33,"-2.5401972"
     +//"70000E+01")
      call LHA_get_real(npara,param,value,"Rtu11",Rtu11,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Rtu12",Rtu12,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Rtu13",Rtu13,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Rtu21",Rtu21,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Rtu22",Rtu22,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Rtu23",Rtu23,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Rtu31",Rtu31,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Rtu32",Rtu32,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Rtu33",Rtu33,"-4.4475245"
     +//"70000E+02")
      call LHA_get_real(npara,param,value,"RUU11",RUU11,"9.16834859"
     +//"00000E-01")
      call LHA_get_real(npara,param,value,"RUU12",RUU12,"-3.9926662"
     +//"90000E-01")
      call LHA_get_real(npara,param,value,"RUU21",RUU21,"3.99266629"
     +//"00000E-01")
      call LHA_get_real(npara,param,value,"RUU22",RUU22,"9.16834859"
     +//"00000E-01")
      call LHA_get_real(npara,param,value,"RRu11",RRu11,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRu12",RRu12,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRu13",RRu13,"5.53644960"
     +//"00000E-01")
      call LHA_get_real(npara,param,value,"RRu14",RRu14,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRu15",RRu15,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRu16",RRu16,"8.32752820"
     +//"00000E-01")
      call LHA_get_real(npara,param,value,"RRu21",RRu21,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRu22",RRu22,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRu23",RRu23,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRu24",RRu24,"1.00000000"
     +//"00000E+00")
      call LHA_get_real(npara,param,value,"RRu25",RRu25,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRu26",RRu26,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRu31",RRu31,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRu32",RRu32,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRu33",RRu33,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRu34",RRu34,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRu35",RRu35,"1.00000000"
     +//"00000E+00")
      call LHA_get_real(npara,param,value,"RRu36",RRu36,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRu41",RRu41,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRu42",RRu42,"1.00000000"
     +//"00000E+00")
      call LHA_get_real(npara,param,value,"RRu43",RRu43,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRu44",RRu44,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRu45",RRu45,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRu46",RRu46,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRu51",RRu51,"1.00000000"
     +//"00000E+00")
      call LHA_get_real(npara,param,value,"RRu52",RRu52,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRu53",RRu53,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRu54",RRu54,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRu55",RRu55,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRu56",RRu56,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRu61",RRu61,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRu62",RRu62,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRu63",RRu63,"8.32752820"
     +//"00000E-01")
      call LHA_get_real(npara,param,value,"RRu64",RRu64,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRu65",RRu65,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"RRu66",RRu66,"-5.5364496"
     +//"00000E-01")
      call LHA_get_real(npara,param,value,"RCKM11",RCKM11,"5.730325"
     +//"9500000E-01")
      call LHA_get_real(npara,param,value,"RCKM12",RCKM12,"8.148918"
     +//"9100000E-01")
      call LHA_get_real(npara,param,value,"RCKM13",RCKM13,"4.688540"
     +//"2900000E-02")
      call LHA_get_real(npara,param,value,"RCKM21",RCKM21,"-8.12592"
     +//"1150000E-01")
      call LHA_get_real(npara,param,value,"RCKM22",RCKM22,"5.627017"
     +//"5700000E-01")
      call LHA_get_real(npara,param,value,"RCKM23",RCKM23,"1.514473"
     +//"3200000E-01")
      call LHA_get_real(npara,param,value,"RCKM31",RCKM31,"9.770056"
     +//"3700000E-02")
      call LHA_get_real(npara,param,value,"RCKM32",RCKM32,"-1.25354"
     +//"0120000E-01")
      call LHA_get_real(npara,param,value,"RCKM33",RCKM33,"9.846211"
     +//"7400000E-01")
      call LHA_get_real(npara,param,value,"RVV11",RVV11,"9.72557835"
     +//"00000E-01")
      call LHA_get_real(npara,param,value,"RVV12",RVV12,"-2.3266124"
     +//"90000E-01")
      call LHA_get_real(npara,param,value,"RVV21",RVV21,"2.32661249"
     +//"00000E-01")
      call LHA_get_real(npara,param,value,"RVV22",RVV22,"9.72557835"
     +//"00000E-01")
      call LHA_get_real(npara,param,value,"Msl6",Msl6,"2.0686780500"
     +//"000E+02")
      call LHA_get_real(npara,param,value,"Msl5",Msl5,"2.0291569000"
     +//"000E+02")
      call LHA_get_real(npara,param,value,"Msl4",Msl4,"2.0291569000"
     +//"000E+02")
      call LHA_get_real(npara,param,value,"Msl3",Msl3,"1.4410279900"
     +//"000E+02")
      call LHA_get_real(npara,param,value,"Msl2",Msl2,"1.4410279900"
     +//"000E+02")
      call LHA_get_real(npara,param,value,"Msl1",Msl1,"1.3449086400"
     +//"000E+02")
      call LHA_get_real(npara,param,value,"MD",MD,"0.00000000E+00")
      call LHA_get_real(npara,param,value,"MU",MU,"0.00000000E+00")
      call LHA_get_real(npara,param,value,"MS",MS,"0.00000000E+00")
      call LHA_get_real(npara,param,value,"MC",MC,"0.00000000E+00")
      call LHA_get_real(npara,param,value,"MB",MB,"4.8899165100000E"
     +//"+00")
      call LHA_get_real(npara,param,value,"MT",MT,"1.7500000000000E"
     +//"+02")
      call LHA_get_real(npara,param,value,"ME",ME,"0.00000000E+00")
      call LHA_get_real(npara,param,value,"Mnue",Mnue,"0.00000000E+"
     +//"00")
      call LHA_get_real(npara,param,value,"MM",MM,"0.00000000E+00")
      call LHA_get_real(npara,param,value,"Mnum",Mnum,"0.00000000E+"
     +//"00")
      call LHA_get_real(npara,param,value,"MTA",MTA,"1.777000000000"
     +//"0E+00")
      call LHA_get_real(npara,param,value,"Mnut",Mnut,"0.00000000E+"
     +//"00")
      call LHA_get_real(npara,param,value,"MZ",MZ,"9.1187600000000E"
     +//"+01")
      call LHA_get_real(npara,param,value,"MW",MW,"7.9829013114276E"
     +//"+01")
      call LHA_get_real(npara,param,value,"Mh01",Mh01,"1.1089905700"
     +//"000E+02")
      call LHA_get_real(npara,param,value,"MH02",MH02,"3.9996011600"
     +//"000E+02")
      call LHA_get_real(npara,param,value,"MA0",MA0,"3.995839170000"
     +//"0E+02")
      call LHA_get_real(npara,param,value,"MH",MH,"4.0787901200000E"
     +//"+02")
      call LHA_get_real(npara,param,value,"Mdsq1",Mdsq1,"5.13065179"
     +//"00000E+02")
      call LHA_get_real(npara,param,value,"Musq1",Musq1,"3.99668493"
     +//"00000E+02")
      call LHA_get_real(npara,param,value,"Mdsq2",Mdsq2,"5.43726676"
     +//"00000E+02")
      call LHA_get_real(npara,param,value,"Musq2",Musq2,"5.49259265"
     +//"00000E+02")
      call LHA_get_real(npara,param,value,"Mdsq3",Mdsq3,"5.45228462"
     +//"00000E+02")
      call LHA_get_real(npara,param,value,"Musq3",Musq3,"5.49259265"
     +//"00000E+02")
      call LHA_get_real(npara,param,value,"Msn1",Msn1,"1.8470846400"
     +//"000E+02")
      call LHA_get_real(npara,param,value,"Msn2",Msn2,"1.8525832600"
     +//"000E+02")
      call LHA_get_real(npara,param,value,"Msn3",Msn3,"1.8525832600"
     +//"000E+02")
      call LHA_get_real(npara,param,value,"Mglu",Mglu,"6.0771370400"
     +//"000E+02")
      call LHA_get_real(npara,param,value,"Mneu1",Mneu1,"9.66880686"
     +//"00000E+01")
      call LHA_get_real(npara,param,value,"Mneu2",Mneu2,"1.81088157"
     +//"00000E+02")
      call LHA_get_real(npara,param,value,"Mch1",Mch1,"1.8169647400"
     +//"000E+02")
      call LHA_get_real(npara,param,value,"Mneu3",Mneu3,"-3.6375602"
     +//"70000E+02")
      call LHA_get_real(npara,param,value,"Mneu4",Mneu4,"3.81729382"
     +//"00000E+02")
      call LHA_get_real(npara,param,value,"Mch2",Mch2,"3.7993932000"
     +//"000E+02")
      call LHA_get_real(npara,param,value,"Mdsq4",Mdsq4,"5.45228462"
     +//"00000E+02")
      call LHA_get_real(npara,param,value,"Musq4",Musq4,"5.61119014"
     +//"00000E+02")
      call LHA_get_real(npara,param,value,"Mdsq5",Mdsq5,"5.68441109"
     +//"00000E+02")
      call LHA_get_real(npara,param,value,"Musq5",Musq5,"5.61119014"
     +//"00000E+02")
      call LHA_get_real(npara,param,value,"Mdsq6",Mdsq6,"5.68441109"
     +//"00000E+02")
      call LHA_get_real(npara,param,value,"Musq6",Musq6,"5.85785818"
     +//"00000E+02")
      call LHA_get_real(npara,param,value,"Wsl6",Wsl6,"2.6990609600"
     +//"000E-01")
      call LHA_get_real(npara,param,value,"Wsl5",Wsl5,"2.1612162600"
     +//"000E-01")
      call LHA_get_real(npara,param,value,"Wsl4",Wsl4,"2.1612162600"
     +//"000E-01")
      call LHA_get_real(npara,param,value,"Wsl3",Wsl3,"8.0156629400"
     +//"000E-01")
      call LHA_get_real(npara,param,value,"Wsl2",Wsl2,"1.1529729200"
     +//"000E+00")
      call LHA_get_real(npara,param,value,"Wsl1",Wsl1,"1.4832726800"
     +//"000E-01")
      call LHA_get_real(npara,param,value,"WT",WT,"1.5619498300000E"
     +//"+00")
      call LHA_get_real(npara,param,value,"WZ",WZ,"2.4114331600000E"
     +//"+00")
      call LHA_get_real(npara,param,value,"WW",WW,"2.0028219600000E"
     +//"+00")
      call LHA_get_real(npara,param,value,"Wh01",Wh01,"1.9861079900"
     +//"000E-03")
      call LHA_get_real(npara,param,value,"WH02",WH02,"5.7480138900"
     +//"000E-01")
      call LHA_get_real(npara,param,value,"WA0",WA0,"6.321784880000"
     +//"0E-01")
      call LHA_get_real(npara,param,value,"WH",WH,"5.4696281300000E"
     +//"-01")
      call LHA_get_real(npara,param,value,"Wdsq1",Wdsq1,"3.73627601"
     +//"00000E+00")
      call LHA_get_real(npara,param,value,"Wusq1",Wusq1,"2.02159578"
     +//"00000E+00")
      call LHA_get_real(npara,param,value,"Wdsq2",Wdsq2,"1.15297292"
     +//"00000E+00")
      call LHA_get_real(npara,param,value,"Wusq2",Wusq2,"2.58585079"
     +//"00000E+00")
      call LHA_get_real(npara,param,value,"Wdsq3",Wdsq3,"2.48689510"
     +//"00000E+00")
      call LHA_get_real(npara,param,value,"Wusq3",Wusq3,"2.85812308"
     +//"00000E-01")
      call LHA_get_real(npara,param,value,"Wsn1",Wsn1,"1.4751897700"
     +//"000E-01")
      call LHA_get_real(npara,param,value,"Wsn2",Wsn2,"1.4988163400"
     +//"000E-01")
      call LHA_get_real(npara,param,value,"Wsn3",Wsn3,"1.4988163400"
     +//"000E-01")
      call LHA_get_real(npara,param,value,"Wglu",Wglu,"5.5067543800"
     +//"000E+00")
      call LHA_get_real(npara,param,value,"Wneu1",Wneu1,"0.00000000"
     +//"E+00")
      call LHA_get_real(npara,param,value,"Wneu2",Wneu2,"2.07770048"
     +//"00000E-02")
      call LHA_get_real(npara,param,value,"Wch1",Wch1,"1.7041450300"
     +//"000E-02")
      call LHA_get_real(npara,param,value,"Wneu3",Wneu3,"1.91598495"
     +//"00000E+00")
      call LHA_get_real(npara,param,value,"Wneu4",Wneu4,"5.47719539"
     +//"00000E+00")
      call LHA_get_real(npara,param,value,"Wch2",Wch2,"5.3127877200"
     +//"000E+00")
      call LHA_get_real(npara,param,value,"Wdsq4",Wdsq4,"5.47719539"
     +//"00000E+00")
      call LHA_get_real(npara,param,value,"Wusq4",Wusq4,"5.31278772"
     +//"00000E+00")
      call LHA_get_real(npara,param,value,"Wdsq5",Wdsq5,"2.85812308"
     +//"00000E-01")
      call LHA_get_real(npara,param,value,"Wusq5",Wusq5,"2.13682161"
     +//"00000E-01")
      call LHA_get_real(npara,param,value,"Wdsq6",Wdsq6,"2.13682161"
     +//"00000E-01")
      call LHA_get_real(npara,param,value,"Wusq6",Wusq6,"7.37313275"
     +//"00000E+00")
