###########################################################
##							 ##
##		ordering width information		 ##
##		**************************		 ##
##							 ##
##	Authors: Pierre Artoisenet (UCL-CP3)		 ##
##	         Olivier Mattelaer (UCL-CP3)		 ##
##							 ##
###########################################################
##    file generated automatically                       ##
##	Transfer functions type : uniform		 ##
###########################################################
## TAG         VALUE
  DELTA          	
  THIN 	       m,e
  LARGE        a,b,t,j,g
   X                1
