###########################################################
##							 ##
##		ordering width information		 ##
##		**************************		 ##
##							 ##
##	Authors: Pierre Artoisenet (UCL-CP3)		 ##
##	         Olivier Mattelaer (UCL-CP3)		 ##
##							 ##
###########################################################
##    file generated automatically                       ##
##	Transfer functions type : all_delta		 ##
###########################################################
## TAG         VALUE
  DELTA        j,b,g,e,m,t  	
  THIN 	       a
  LARGE        
   X                0
