# Makefile automatically generated by bomrelease version 1.17 (2008/11/18 22:15:54)
#
# timeout version 4.09 (2009-03-02)

PROGRAM = timeoutSSP
SOURCE  = stderr.c timeout.c
OBJECT  = stderr.o timeout.o
DEBRIS  = a.out core *~
OFLAGS  = -g
WFLAGS  = # -Wall -Wmissing-prototypes -Wstrict-prototypes -std=c89 -pedantic
UFLAGS  = # Set on command line only
IFLAGS  = # -I directory options
DFLAGS  = # -D define options
CFLAGS  = ${OFLAGS} ${UFLAGS} ${WFLAGS} ${IFLAGS} ${DFLAGS}


all: ${PROGRAM}

${PROGRAM}: ${OBJECT}
	${CC} -o $@ ${CFLAGS} ${OBJECT} ${LDFLAGS} ${LDLIBES}

clean:
	rm -f ${OBJECT} ${DEBRIS}

realclean: clean
	rm -f ${PROGRAM}

depend: ${SOURCE}
	mkdep -ftimeout.mk ${SOURCE}

# DO NOT DELETE THIS LINE or the blank line after it -- make depend uses them.

stderr.o: stderr.c
stderr.o: stderr.h
timeout.o: stderr.h
timeout.o: timeout.c
