###########################################################
##							 ##
##		ordering width information		 ##
##		**************************		 ##
##							 ##
##	Authors: Pierre Artoisenet (UCL-CP3)		 ##
##	         Olivier Mattelaer (UCL-CP3)		 ##
##							 ##
###########################################################
##    file generated automatically                       ##
$$name_TF
###########################################################
## TAG         VALUE
  DELTA        $$order_delta$$  	
  THIN 	       $$order_thin$$
  LARGE        $$order_large$$
